### PR TITLE
Transcode finished fix

### PR DESCRIPTION
**Pull request by thomabx**
**Changes**
Player was not terminating at end of duration with transcoded files and would loop end of video. 

This uses the timer from videos's position (default is 0.5 seconds) to check the current playback position and forces playback to end when the duration is met. There probably is a more elegant solution to this.

### CODE REVIEW

**Comment by bisby** [comment]
For the record, it makes it trickier to evaluate the PR when it is forked off your previous branch and not master. I'll be reviewing these today, but it might take a minute.

**Comment by thomabx** [comment]
I haven't contributed to a project before. I'll keep that in mind.

**Comment by bisby** [comment]
No worries at all! Really appreciate your contributions.

Isolated changes just make it easier (for me) to check the changes specific to the topic at hand. And *IF* for whatever reason the other PR is rejected (or changes requested), then this one doesn't have to be as well.

(And as such I'll have to review the other PR first)

**Comment by bisby** [comment]
Also, this now seems to have rebasing issues, because it claims it is updating files that were already merged in the other PR.

If you could rebase the single commit relevant to the PR and push it up, I think that may fix things? Github PR's can be sorta touchy.

**Pull request closed without merging**
