### PR TITLE
Fix music shuffle function

### LINKED ISSUE #1172: Audio shuffle mode no longer works
## Software Versions

- Jellyfin Server Version:  10.8.9
- Roku Client Version:  1.6.4

## Describe the bug
Shuffle songs during audio playback no longer works.

## How To Reproduce

1. Play an music album
2. Click the shuffle button to enable shuffle mode
3. Once the song ends, it will continue to the next track and shuffle will turn off by itself

## Expected behavior
Shuffle mode should remain on, and playback of songs should be shuffled.

## Additional context
I fixed a similar issue with the loop functionality. It's likely I hit a piece of code when fixing that issue and inadvertently caused this issue.

### PR DESCRIPTION
**Pull request by 1hitsong**
## Changes
Fixes music shuffle functionality. Moves shuffle responsibility out of audio player view and to the queue manager.

## Issues
Fixes #1172

### CODE REVIEW

**Review by cewert — CHANGES_REQUESTED** [review]
This works well and I can't break it but I have a couple questions:

- If you have shuffle OFF then skip to the last track in the playlist, then turn shuffle ON, you can now skip forward the full length of the playlist again. Is this intentional? I think Spotify does the same thing so I'm assuming it is but thought I'd ask

- The "Track X/ Y" text gets a bit confusing when using shuffle. For example, mine will say "track 3/ 3" when I'm listening to the second song in the playlist and hitting the next song button takes me to "track 2/ 3". In other words, there is no way to know how many songs are left in the playlist or how many songs I've already played when using the shuffle feature. I think we should fix that but I'm not sure if that should be a part of this PR or how much work that would entail. What do you think?

**Comment by 1hitsong** [comment]
> If you have shuffle OFF then skip to the last track in the playlist, then turn shuffle ON, you can now skip forward the full length of the playlist again. Is this intentional? I think Spotify does the same thing so I'm assuming it is but thought I'd ask

Yes, that's intentional. When a user activates shuffle, the linear progress is set aside and the new shuffled queue is honored with the current track as track 1.

> The "Track X/ Y" text gets a bit confusing when using shuffle. For example, mine will say "track 3/ 3" when I'm listening to the second song in the playlist and hitting the next song button takes me to "track 2/ 3". In other words, there is no way to know how many songs are left in the playlist or how many songs I've already played when using the shuffle feature. I think we should fix that but I'm not sure if that should be a part of this PR or how much work that would entail. What do you think?

I think this should be part of this PR.

The end result should be:
Shuffled Enabled: Shuffled Track Number / Total Tracks
Shuffled Disabled: Linear Track Number / Total Tracks

**Comment by 1hitsong** [comment]
@cewert Changes pushed. Track display now follows this logic:

Shuffled Enabled: Shuffled Track Number / Total Tracks
Shuffled Disabled: Linear Track Number / Total Tracks

**Review by cewert — APPROVED** [review]
Still works and the track numbers update like you said 👍

**Pull request merged**
