### PR TITLE
fix overviewdialog ok button

### LINKED ISSUE #1005: OverviewDialog OK button does not work
Pressing "OK" on the overview dialog titled "Press OK to Close" does not close the dialog.
This dialog is located in PersonDetails, and is shown when you click an ellipsized text description.

### PR DESCRIPTION
**Pull request by sevenrats**
**Changes**
dont check the focus chain while listening for "OK" in overviewdialog

**Issues**
fixes #1005

### CODE REVIEW

**Review by candry7731 — APPROVED** [review]

**Comment by sevenrats** [comment]
This fixes the  overview dialog when ellipsized text is expanded from a PersonDetails.  To reproduce the relevant issue:
1) start the app
2) select a movie library, select a movie
3) select a person with an ellipsized text description from the  cast row of the extras slider.
4) click the ellipsized text description of the PersonDetails to create a StandardDialog titled "Press OK to close"
5) Pressing "OK" does nothing, and back must be pressed to close the StandardDialog

**Comment by 1hitsong** [comment]
@sevenrats I can't recreate. I tried on over 2 dozen people and pressing "OK" closed the dialog in all instances.

**Comment by sevenrats** [comment]
> @sevenrats I can't recreate. I tried on over 2 dozen people and pressing "OK" closed the dialog in all instances.

would you please try again now that my new persondetails view is merged? its possible i broke it my own self.

**Comment by 1hitsong** [comment]
Retested `unstable` and pressing OK closes the popup just fine.

**Comment by sevenrats** [comment]
lol what a nightmare.
I have confirmed the opposite repeatedly on mine.
I think next step is, I will submit a video of the event and my roku model number, maybe it will be clear to somebody what the difference is.

**Comment by Gartral** [comment]
Can confirm that as of commit 747b2e0 on a Roku Express+ HD (3910RW) pressing OK to close the expanded info window of a cast member does bumkiss.

**Comment by candry7731** [comment]
seems to me that when the cast as scrollable data the ok opens and closes the created StandardDialog.

However when Pressing ok on a cast that does not have scrollable data it does create the StandardDialog. however pressing ok again to close does nothing and you must press back to close the dialog. again this is for a cast member that does not have scrollable data in the StandardDialog box.

**Comment by sevenrats** [comment]
Candry nailed this. This is exactly the behavior I observe.  Can you confirm or deny @1hitsong? Is it possible you tested all people with ellipsized text?

**Comment by cewert** [comment]
I was able to reproduce on latest version of `unstable`. I used the movie Trading Places and was able to reproduce the error on several cast members. There was no obvious pattern to me. Some had ellipsis, some didn't. Some picture, some not. Although it seemed that the cast at the end of the list with no metadata seemed to show the bug more consistently.

**Review by cewert — CHANGES_REQUESTED** [review]
So, at first I thought your PR may have fixed the issue but then I realized the person view where the bug exists is different on your PR than unstable (mainly the favorite button moved).

Once I merged your branch with unstable, I was able to reproduce the bug consistently on the same people as before on the unstable branch.

**Pull request closed without merging**
