### PR TITLE
Implement Version selection for Movies

### LINKED ISSUE #531: Roku app - Cant select different movie versions
I am on the newest Roku channel app and I have no options to change the movie version, it defaults to the 4k version of the file. From the web I can see 2 versions 4k and 1080 and it lets me choose which one I want to play. The only options it gives me on the roku app is to adjust the audio channel.

### PR DESCRIPTION
**Pull request by jimdogx**
Allows user to select between different versions of a movie (if available)

**Changes**
Adds "Version" along side the existing Audio, Watched and Favorite options on the Movie Details screen.

**Issues**
Fixes: #531

### CODE REVIEW

**Comment by jimdogx** [comment]
I only have one movie with more than one version on the server I connect to.  Would be great if someone else could test this and make sure it works for them as well. 👍

**Comment by debmint** [comment]
> I only have one movie with more than one version on the server I connect to. Would be great if someone else could test this and make sure it works for them as well.

I have a movie or two with multiple versions and I've felt  for a while that this is another feature that has been much needed.  Looking forward to trying it out.

**Comment by jimdogx** [comment]
> > I only have one movie with more than one version on the server I connect to. Would be great if someone else could test this and make sure it works for them as well.
> 
> I have a movie or two with multiple versions and I've felt for a while that this is another feature that has been much needed. Looking forward to trying it out.

Thanks!  I'd hold off for a bit as I found one small thing I'm trying to fix.  I'll change it from Draft to Ready for Review once I push a fix.

**Comment by neilsb** [comment]
There's something funny going on for me with a test setup.  I've got a movie with 2 versions, and it seems to work fine on them.  I added another test video file (30 seconds long) and renamed it to match the movie, and it appears fine in the list and plays as expected on Web.  But selecting that version on the Roku plays the default movie version.  Yet on the dashboard it shows the movie playing is only 30s long.   I'll do some more debugging on this later and get back to you.

On the UI, side of things, would it be worth considering changing the "Audio" button to just "Options" or "Settings" or something, and have the Video & Audio selection in the same popup, just different tabs (like how the Movie Grid option screen has tabs for View / Sort / Filter)?   This could allow us (at a later date) to also add Subtitles in there too, allowing them to be selected before starting the movie?

And sorry, for introducing conflicts by merging the Movie Extra PR into master. :/

**Comment by jimdogx** [comment]
> There's something funny going on for me with a test setup...

Dang it, I didn't think to try with 3 versions.

> On the UI, side of things, would it be worth considering changing the "Audio" button to just "Options" or "Settings" or something, and have the Video & Audio selection in the same popup...

Good idea... I might be short on time for a few weeks.  I'll try to take a look today.

> And sorry, for introducing conflicts by merging the Movie Extra PR into master. :/

Conflicts are a part of life and as far as conflicts go, that was an easy one 😄

**Comment by jimdogx** [comment]
I figured out the playback issue with more than 2 versions.  👍   Just testing now...

**Comment by jimdogx** [comment]
Looks like it's working on my end.

Don't think I'll have time to work on the UI suggestion by @neilsb any time soon.  I also don't want to hold up a release (I figure one is coming soon, lots of good stuff waiting in the wings).

I'd suggest setting this PR to Draft *or* moving forward with the PR as is and whenever someone adds subtitles it can be changed to a single popup. 👍

**Review by neilsb — APPROVED** [review]
You - agree with that.  Can tidy up the UI at a later date.

Works fine now for me too.  👍

**Comment by debmint** [comment]
tried to reply via email but hasn't showed up.  May be a delay so there may be two replies here
 
> On the UI, side of things, would it be worth considering changing the "Audio" button to just "Options" or "Settings" or something, and have the Video & Audio selection in the same popup, just different tabs (like how the Movie Grid option screen has tabs for View / Sort / Filter)? This could allow us (at a later date) to also add Subtitles in there too, allowing them to be selected before starting the movie?

I like this modification but feel it might need a little different approach.  Could this be done by enabling optionsAvailable and doing both through use of star button?  As is, there is no indication as to whether there are multiple sources without clicking the Videos button.  If the current UI is kept, how about having the text for the button (and possibly for Audio, too) grayed out if there are no choices.  Another option is to simply not display the button if there are no choices.  I tried to do this but it appears that you cannot fiddle around with the buttons for a ButtonGroup.  I first tried leaving the ButtonGroupHoriz empty and dynamically adding the buttons, but found that did not work.  the buttons field for a BG are not defined as Buttons but the text field for the button.  By simply adding buttons in this way, you wouldn't have the "id" which is used by the callback for when the button is clicked.  You could possibly add a check for the "text" after the other checks, I suppose.  I did come up with a solution.  I changed the "ButtonGroupHoriz" to "LayouutGroup", then adding the buttons programatically - Video only if multiple sources.  I had to provide the logic to handle left/right button clicks, etc, but it works.  If there is any interest in this,I can push it to my fork for you al to examine.  If I do this, will I need to post a PR to make it easier for give you access?

**Comment by jimdogx** [comment]
> Video only if multiple sources. I had to provide the logic to handle left/right button clicks, etc, but it works. If there is any interest in this,I can push it to my fork for you al to examine.

I was thinking about this a little too (not showing the option if there was only one version).  Things can always be improved, but at some point you have to ship what you got and keep improving for the next release (users are waiting for all these great features!!! 😄 ).

>  If I do this, will I need to post a PR to make it easier for give you access?

This PR is closed / merged so any improvements should be a new PR 👍

**Comment by debmint** [comment]
> > If I do this, will I need to post a PR to make it easier for give you access?
> 
> This PR is closed / merged so any improvements should be a new PR +1

Yes, I know. I pushed it to my fork as a branch named "hideVideosIfOneMediaSource".  If you can clone it as is I'd rather not clutter up this place with a possibly useless PR. If you do examine it and like it, just take it and apply it to your work.  I'd prefer for you to handle this modification yourself since you started it.  I had thought about adding this feature myself, but am glad you jumped on it.  Again, if doing a PR would make it better, I can do that, but feel free to handle it however you want.

I believe you replied to my original post.  Should I delete this second one?  I don't see the original here.

**Comment by jimdogx** [comment]
> If you do examine it and like it, just take it and apply it to your work.

I'd have to open a new PR anyway 😄 

Just an FYI, I'm strapped for time the next two weeks, so probably won't get any Roku dev time in.  So if you don't hear from me, I'm not ignoring you haa haa.  This also might be an argument for just making it a new PR as someone else (Neil etc) could check it out and merge it if they agree. 👍

**Comment by TwitchBronBron** [comment]
Just my two cents, I'd definitely prefer not hiding that functionality behind the star button press. Seems to be a little too hidden. If the user can't find the feature, it doesn't exist. Even just today, my mom couldn't find the search functionality on the main page because she's used to other apps where the search functionality is more visible. 

So all that to say, I like the "options" button way more.

**Comment by debmint** [comment]
> Just an FYI, I'm strapped for time the next two weeks, ... This also might be an argument for just making it a new PR as someone else (Neil etc) could check it out and merge it if they agree.

I might put it up maybe as a draft.  I'm not sure if it is all that solid, but it will expose it for review.  To be honest, I like the "options" path Neil suggested.

**Comment by debmint** [comment]
> Just my two cents, I'd definitely prefer not hiding that functionality behind the star button press. Seems to be a little too hidden.

I do agree.  I just mentioned it because this method appears in other screens, although I actually wish these were handled in some other way.  Just how, I'm not sure.

> If the user can't find the feature, it doesn't exist. 

Exactly.  The only problem I have with the current rendition is that unless the user is totally familiar with the movie, he has to click the Video button to even know if there are any choices in Video versions.  Perhaps a good option would be to keep Video and audio separate and then indicate availability of options somehow, perhaps by text color.  probably ought to not disable he button but with experience, in the absence of documentation, the user will learn the meaning of the colors, and also would not cause the user to assume that something is not working if he clicks the button and nothing happens.

> So all that to say, I like the "options" button way more.

I'm going to go ahead and post a PR on what I've done to see if that would be an acceptable solution.

**Comment by neilsb** [comment]
I'm of the same opinion that using the * button here wouldn't be the best idea.

> Exactly. The only problem I have with the current rendition is that unless the user is totally familiar with the movie, he has to click the Video button to even know if there are any choices in Video versions.

Could quite easily have a superscript count of the other tracks/streams available on the main media details page, which the user could toggle via the settings if they didn't want it.

e.g.

Video:  720p H264 SDR <sup>+1</sup>
Audio:  Surround - Eng - Dolby Digital - 5.1. - Default <sup>+3</sup>

And if it's moved to a single options button, could also have the tab names contain the number of options to save them having to select the appropriate tab to see if there are options avaialble

Audio (3) | Video (2) | Subtitles (1)

**Comment by debmint** [comment]
On Sun, Mar 13, 2022 at 4:13 AM Neil Burrows ***@***.***>
wrote:

> On the UI, side of things, would it be worth considering changing the
> "Audio" button to just "Options" or "Settings" or something, and have the
> Video & Audio selection in the same popup, just different tabs (like how
> the Movie Grid option screen has tabs for View / Sort / Filter)? This could
> allow us (at a later date) to also add Subtitles in there too, allowing
> them to be selected before starting the movie?
>
This sounds like a good idea.  Or perhaps enabling the options menu for
this screen? In addition, it seems we need to   have some sort of
indication whether there are multiple  sources.  I've been playing around
with dynamically setting up the buttons row, but from what I can gather,
ButtonGroup does not allow fiddling around with the buttons, although there
might be a way that I didn't discover.  I tried creating a series of
buttons - adding a "Version" button only if .mediaSources > 1 only to
discover that BG.buttons are defined by the strings for the text field for
the button thus not having an "id", which is used by the callback to
determine what you want.  I guess you could, after doing the other checks,
possibly check the text field. After abandoning this approach, What I
finally did was change the ButtonGroupHoriz to a LayoutGroup  and doing all
the focusing, etc from with MovieDetails.brs.  If this sounds like it might
be viable, I can create a branch on my fork and you can check it out.

> And sorry, for introducing conflicts by merging the Movie Extra PR into
> master. :/
>
Was this something that I caused or just normal conflicts?  This is my
first attempt at contributing to a collaborative project.

**Comment by jimdogx** [comment]
@debmint Did you mean to comment on this PR?  It's been merged / closed since March.  And some of the suggestions here have already been implemented in other PRs.  Here is a screenshot of the latest, including changing "audio" to "options" and showing the user when there is more than one video version (with the "+1"): 

Screen Shot 2022-10-11 at 6 19 05 AM

**Pull request merged**
