### PR TITLE
Add .vscode and logs to git ignore

### PR DESCRIPTION
**Pull request by neilsb**
**Changes**
Update .gitignore to ignore the following
- **.vscode** - VisualStudio Code local project configuration files
- **logs** - log folder

### CODE REVIEW

**Comment by neilsb** [comment]
The _BrightScript Language_ extension for VSCode is very nice - if you've not tried it.  The integrated debugging is handy.  :)

**Comment by cewert** [comment]
The code formatting is great too. Should we add a launch config before we add this to .gitignore?

**Comment by neilsb** [comment]
Not sure - mine is just the default values that were created by the extension (with the exception of the Roku host & password).

**Review by cewert — APPROVED** [review]
My launch config is setup to run `make prep_staging` then use the output files. I thought others would need to do the same but I just tried using the defaults and it seems to work just as well.

**Pull request merged**
