### PR TITLE
Add Music Artist section navigation

### PR DESCRIPTION
**Pull request by 1hitsong**
**Changes**
Add a small navigation section to the left of the Music Artist screen. Currently it only shows details and albums, but this is the start of adding new data to the screen, such as Appears on, Related Artists, etc.

This will prevent users from needing to scroll down through every section to find what they're looking for.

`ropm install` required to install components.

**Example**
See it in action: https://twitter.com/1hitsong/status/1563676591661715456

### CODE REVIEW

**Review by neilsb — APPROVED** [review]

**Comment by cewert** [comment]
> This will prevent users from needing to scroll down through every section to find what they're looking for.

Not sure where to post this at the moment but I'm having a hard time wrapping my head around how this prevents scrolling or makes anything easier. I can either hit down once to view extras the "normal" way or I can use your menu to view extras by hitting "left", "down", and then "okay". So your new menu takes two extra clicks or button presses or whatever you want to call it to get to the same information. And I still have to "scroll" your new menu the same way I would have to scroll normally.

**Comment by 1hitsong** [comment]
Here's an example where it saves time where I'm wanting to get to the Appears On section. You can count the clicks.

https://user-images.githubusercontent.com/3330318/226705634-56fbc2d1-d2c4-4a03-8a17-3a9340ae109c.mp4

**Comment by cewert** [comment]
So it only saves clicks for artists which you have a lot of albums for. If the artist you're viewing has <=10 albums it will waste clicks and >10 but <= 15 would be a wash if my math is right.

In your example it was an artist who has 22 albums (when you scroll the artist page it only shows 21 items under Albums but the library view says 22. Is that a bug?) and it saved you 2 clicks. It's also only saving clicks in your example because of how you chose to implement the Albums section - having an infinite amount of rows vs having one wrappable row with all the albums listed like on our home screen.

Are you planning on implementing this for the other library types? If the goal is to save clicks then I'm not sure it would make sense to do that because of how the other libraries are implementing their "extras" section - they don't have a section that could be 1-10+ rows. And in that scenario I'm not sure it makes sense to have one library type have two different navigation methods. More opportunities for bugs, not sure which navigation method is quicker unless you do math on the number of albums, and generally speaking would make the app more confusing to navigate instead of making it easier IMO since navigation depends on library type.

**Comment by 1hitsong** [comment]
> In your example it was an artist who has 22 albums (when you scroll the artist page it only shows 21 items under Albums but the library view says 22. Is that a bug?) and it saved you 2 clicks.

Consider the future as well. Eventually there will be other sections on this page, such as Similar Artists.

> It's also only saving clicks in your example because of how you chose to implement the Albums section - having an infinite amount of rows vs having one wrappable row with all the albums listed like on our home screen.

Yep. That scrolling album row was a UX nightmare, I hated that thing.

> Are you planning on implementing this for the other library types?

I hadn't planned on it at this point. I'm not sure it's applicable.

**Comment by cewert** [comment]
> Yep. That scrolling album row was a UX nightmare, I hated that thing.

What? Why? Are you saying you hate using the home page of our app? Having one wrappable row of items is a very "Roku" way of doing things. It's a predictable way of finding the album you're looking for - keep tapping "right" while scanning the images/titles. The way you have it implemented I have to scan each row of items to see where the album I'm looking for is. I will know vaguely where it's at based on album name but i won't know which row it's on till i navigate and skim them. Neither method is "easy" but i prefer having just one row. And If i wanted to listen to a specific album it would probably be easier to search for it anyway, right? That would be faster than either method.

> Consider the future as well. Eventually there will be other sections on this page, such as Similar Artists.

I think having the app be as consistent as possible and easy to use is more important than saving a few clicks for people who happen to have artists with more than 15 albums.

I also think this menu is completely unnecessary and that having one row that's wrappable would be a better implementation than having dozens of rows and needing a whole new menu just to navigate it.

I also don't understand why you are implementing completely new menus just for music when from the beginning you said you wanted to start with an MVP and build up. Having a fancy new menu just to save a few clicks for specific artists would be at the bottom of my personal priority list and is also not mentioned anywhere on your [music player roadmap](https://github.com/jellyfin/jellyfin-roku/discussions/608)

**Comment by 1hitsong** [comment]
> What? Why?

IMO seeing as many albums as possible is better than only seeing 7 or 8. It's simply an item grid view, which we use for libraries, why not use it here for albums as well.

> Are you saying you hate using the home page of our app?

Nope. I didn't say anything about the home view.

> I also think this menu is completely unnecessary and that having one row that's wrappable would be a better implementation than having dozens of rows and needing a whole new menu just to navigate it.

Feel free to turn it into a setting and allow users to select which presentation they want to use. I like it this way though.

> I also don't understand why you are implementing completely new menus just for music when from the beginning you said you wanted to start with an MVP and build up. Having a fancy new menu just to save a few clicks for specific artists would be at the bottom of my personal priority list

I use the music player every day. I got tired on having to press down so much. This was my idea to stream line it a bit, and it works. 😄

**Comment by cewert** [comment]
> IMO seeing as many albums as possible is better than only seeing 7 or 8. It's simply an item grid view, which we use for libraries, why not use it here for albums as well.

Because the item grid view takes up the whole screen. You can scroll up or down as much as you want and you stay within the itemgrid vs what you're doing where you basically threw an itemgrid in the middle of screen that users must scroll up or down to "open" or "close" it. Why not use it here? because you can't predict how big it will be and will then need to make a whole separate menu just to deal with it lol.

> Nope. I didn't say anything about the home view.

Then why did you hate scrolling to find an album? You don't mind doing it on the home screen to find a library or recently watched movie or whatever but doing it for an album was too much?

> Feel free to turn it into a setting and allow users to select which presentation they want to use. I like it this way though.

Great point. Why make the new menu on by default? If you had it off by default that would be a decent compromise. It would make the UI consistent and easy to use for the avg Joe (i.e. your elderly relative that you set up jellyfin for) and the music heads who have hundreds and hundreds of albums would have a user setting they could turn on in case they get tired of pressing down so much.

**Pull request merged**
