### PR TITLE
Add Max Audio Channel condition to supported codecs

### LINKED ISSUE #267: Scrambled OPUS Audio
When playing an .MKV file with a 720p HEVC video stream, and a "Jpn OPUS 5.1 Default" audio stream, the audio is heavily scrambled.
Mostly, only loud static noise can be heard. The natural sound from the audio stream can be barely heard, though also scrambled.

Works fine on the web version of Jellyfin.
Probably a transcoding error. May be related to #231

### LINKED ISSUE #491: 1.4.9 Transcoding issues 7.1
**1.4.9 Transcoding issues**
< Just updated to newest version and any file with 7.1 audio no longer transcodes. Reverting back to 1.4.7 fixes issue>

**To Reproduce**

1. Update to newest version'
2. Play file with 7.1 audio
3. Video plays but no sound is heard

**Expected behavior**
<Jellyfin remxxes or transcodes 7.1 audio to stereo so its compatible with my devices>

**Logs**
<https://pastebin.com/iEbkE3BN>

**Additional context**
<1.4.7 and 1.4.8 work perfectly and allow 7.1 audio to be converted to stereo but build 1.4.9 fails to transcode. 5.1 and below audio work fine on all versions>

### PR DESCRIPTION
**Pull request by neilsb**
Server was not providing a transcoding URL when the number of Audio Channels in the media was greater than was supported on the device.

Added a Codec Condition to the Device Profile to specify Audio Channels must be less than or equal to the number supported by the client.

**Issues**
fixes #491
fixes #267

### CODE REVIEW

**Review by anthonylavado — APPROVED** [review]

**Comment by anthonylavado** [comment]
I'll make a beta update for this.

**Comment by itsb** [comment]
> I'll make a beta update for this.

Is this on the Jellyfin beta channel?
I just installed the Jellyfin beta app (Version 1.4 * build 9), but still see the same issue.

Rolling back the main app to 1.4.7 on my Roku ultra resolved the issue.

Thanks,

**Comment by tgiokdi** [comment]
> Rolling back the main app to 1.4.7 on my Roku ultra resolved the issue.

I've not found much documentation on rolling back Roku apps, can you point me in the right direction?

**Comment by neilsb** [comment]
> I've not found much documentation on rolling back Roku apps, can you point me in the right direction?

Not sure you can officially roll back app versions.  There's another couple of bugfixes to be reviewed, but will try and get them into the client in the next few days and get a release out to the store.

**Comment by itsb** [comment]
@tgiokdi, i enabled 'dev' mode on my roku and then uploaded the 1.4.7 release zip file from github to the roku in the developer web UI. It shows up as a second jellyfin app in your home screen. you can check the app version with the star (*) key on your remote.
thanks @neilsb !

**Comment by sunnybreaux** [comment]
Issues still occur on Latest Roku (public) Jellyfin app. Not Transcoding 7.1

Roku Ultra LT
HVEC 7.1 DTS-HD MA
User settings specified max Audio channels

**Pull request merged**
