### PR TITLE
Auto play the next TV episode

### LINKED ISSUE #160: Automatically play next episode
**Automatically play next episode**
There should be an option to automatically play the next episode when an episode of a series finishes. 

**Additional context**
Currently the app kicks you back to the season or series level (seems random?) instead of playing the next episode. This feature was present in the very old version I just updated from and the web version, and it is sorely missed. If there is some option related to this in the app already, we have not been able to find it.

### PR DESCRIPTION
**Pull request by cewert**
This auto plays the next available episode for all videos of type "Episode". Ideally this would be a client user setting but user settings still need a lot of work.

**Changes**
Add `showID` field to JFVideo
Small refactor to `StopPlayback()`
Create `playNextEpisode()` function to lookup and play the next available episode
Fix a typo that was preventing the video title from being passed to the video player

**Issues**
Fixes #160

### CODE REVIEW

**Comment by neilsb** [comment]
Just had a quick play, and look good against 10.6.  However, against unstable (10.7) the API call in `playNextEpisode()` seems to be returning invalid.

**Comment by Artiume** [comment]
sweet and simple, love it. Works for me on 10.6

**Comment by cewert** [comment]
@neilsb My server is on latest stable so I'm unable to test it. Does the server log show anything when the API call fails?

The API call I'm using may not be the best way to to pull the next episode so I'm open to suggestions

**Comment by neilsb** [comment]
> @neilsb My server is on latest stable so I'm unable to test it. Does the server log show anything when the API call fails?

It seems to be returning a valid response, just with no episodes.  Dropping the `StartItemId` seems to return data - so not sure what's going on.  I'll try to have a more in detail look tomorrow.   Apparently there is a "unstable" demo server at  https://demo.jellyfin.org/unstable

**Comment by neilsb** [comment]
Problem is on the server side due to a change in how it compares Guids.  One of the server team is looking at it, so that should allow this to work fine

**Comment by Artiume** [comment]
Should we add in Neil's countdown marker to this PR?

**Comment by neilsb** [comment]
> Should we add in Neil's countdown marker to this PR?

Since it can be dropped on top, I'd say we just merge this one and can raise another one for teh countdown marker thing

**Review by neilsb — APPROVED** [review]

**Pull request merged**
