### PR TITLE
Add appears on music artist section

### PR DESCRIPTION
**Pull request by 1hitsong**
**Changes**
1. Changes music API calls to match web ui. 
2. Adds Appears On section to artist page.

**Issues**
#802

### CODE REVIEW

**Comment by jimdogx** [comment]
I got a crash for a specific artist.  This artist doesn't have an "Album" or "Appears On" even though if I click on the Play button it proceeds to play 8 tracks (my guess is from an album).  This is a remote server so I'm going to see if I can get the folder structure for this artist from the server owner.

```
008:      if m.top.hasFocus()
009:*         m.top.getChild(m.top.selected).setFocus(true)
010:          m.top.focusButton = m.top.selected
011:      end if
012:  end sub
Source Digest(s): 
pkg: dev 1.5.0 9d21af0a Jellyfin

'Dot' Operator attempted with invalid BrightScript Component or interface reference. (runtime error &hec) in pkg:/components/roku_modules/bgv/ButtonGroupVert.brs(9)
Backtrace:
#0  Function bgv_onfocuschanged() As Void
   file/line: pkg:/components/roku_modules/bgv/ButtonGroupVert.brs(9)
Local Variables:

global           Interface:ifGlobal
m                roAssociativeArray refcnt=2 count:2
Threads:
ID    Location                                Source Code
 0    pkg:/source/Main.brs(83)                msg = wait(0, m.port)

 1*   ...dules/bgv/ButtonGroupVert.brs(9)     m.top.getChild(m.top.selected).setFocus(true)
  *selected
```

**Comment by 1hitsong** [comment]
@jimdogx I added an additional check in the case no albums and no appears on items are found. I also put back a check for if there is no album data and no appears on data to fall back into an album of songs view.

What actions did you take to throw the error?

**Comment by jimdogx** [comment]
Getting a different crash now.  I'd wait on additional changes until I can find out what the structure is.

Also, does Album view work for you?  It looks like not matter how I filter the view, it's always Artist.

**Comment by 1hitsong** [comment]
Album view issue resolved. It should work now.

**Comment by jimdogx** [comment]
Album vs Artist view now works.  It was *really* slow to load rows 10-20 (spinner ran forever), both on a remote server and a local server.  But once it was working it was fine.  Guessing some sort of metadata being built up?

**Comment by 1hitsong** [comment]
Was it slow under both views or just one?

**Comment by jimdogx** [comment]
> Was it slow under both views or just one?

Turns out it was most likely the server.

**Review by jimdogx — APPROVED** [review]

**Comment by 1hitsong** [comment]
To be merged 10/7 unless an issue arises.

**Review by alanazar — APPROVED** [review]
Tested it on Roku, worked ok

**Pull request merged**
