### PR TITLE
Do not display Videos button if only one mediaSource

### PR DESCRIPTION
**Pull request by debmint**
**Changes**

Enhancement to commit f789867 where option to choose video source for movie.  This patch eliminates display of
Video button if there is only one media source available

**Issues**

The current rendition does not make it clear whether there are multiple choices for video sources.  Unless the user is totally familiar with a movie, he will have to click the button to even know if there are options.  This version does not display this button if there is only one source.

### CODE REVIEW

**Comment by debmint** [comment]
I would like to have been able to allow the button group to remain as a "ButtonGroupHoriz", but could not find a way to do it.  I attempted to not populate the buttons in the .xml file, then add them bu creating Button objects in the brs file.  This dod not work because the buttons for a ButtonGroup are added as a string for the button's text field, but the "id" is needed because the buttons field is not readable.  I wonder now if these buttons could be retrieved by the GetChildren() call?  I finally just redefined the "ButtonGroupHoriz" to be a "LayoutGroup" and manually added the buttons - "Video" only if mediaSource > 1.

Any suggestions are welcome - if this is even an acceptable solution

**Comment by neilsb** [comment]
So generally this works OK (although, currently when the audio & version buttons are both shown, the "favorite" button disappears off the edge of the screen).

My main struggle with this method over the other you you did is the change the UI based on some attributes of the content.  With buttons sometimes showing and sometimes not showing I feel it may not be entirely clear to the user why this is happening.  "Why on one video is there an audio and version button, but on this other movie I only get an audio button, and this other one I don't get either?"   

My thoughts are that a consistent screen may be better.  So for every movie, to mark it watched you'd select it from the Movie Grid, press right twice times and press ok (for example).  Perhaps rather than having the being hidden, they are visually disabled?

I'm not sure - but would be good to get thoughts from other people.

**Comment by TwitchBronBron** [comment]
I agree. Disabling it is a better user experience than hiding it.

**Comment by debmint** [comment]
> So generally this works OK (although, currently when the audio & version buttons are both shown, the "favorite" button disappears off the edge of the screen).

I thought I had calculated the width so this wouldn't happen

> My main struggle with this method over the other you you did is the change the UI based on some attributes of the content. With buttons sometimes showing and sometimes not showing I feel it may not be entirely clear to the user

Good point.  My main reason for coming up with this method was to eliminate confusion but this could very well be another source of confusion.

> My thoughts are that a consistent screen may be better..... Perhaps rather than having the being hidden, they are visually disabled?

I had thought about this, and would probably be a better way.

> I'm not sure - but would be good to get thoughts from other people.

After trying both versions, I am on the point of preferring the other way best.  I would be fine with dropping this PR and going the other route if that's the consensus of opinion, but if this route is liked, I can develop it further.

**Comment by debmint** [comment]
> I agree. Disabling it is a better user experience than hiding it.

I replied to @neilsb, would appreciate your input also

**Comment by TwitchBronBron** [comment]
I definitely think we should show the version button all the time. How about, instead of show/hide, we could show the number of versions in parentheses next to the button. Then, the version picker could always be enabled, and the user could be aware how many versions are there and not need to click it if there's only 1 version. 

Also, there's a bug in this implementation. When the `Version` button is visible, the `Favorites` button is shoved off screen right, but is still available to click if you move right enough times.

**Comment by neilsb** [comment]
@TwitchBronBron Do you think having the separate Version and Audio buttons is a better UI than the single Options button (#535)?

**Comment by TwitchBronBron** [comment]
Oh right, I forgot about that PR. Yeah, I like the single options menu better than this.

**Comment by debmint** [comment]
> I definitely think we should show the version button all the time. How about, instead of show/hide, we could show the number of versions in parentheses next to the button.   I have the number showing for each of video and audio codecs as per Neil's suggestion.  I suppose you could show the count - even add it to the button label if desired.

> Also, there's a bug in this implementation. When the `Version` button is visible, the `Favorites` button is shoved off screen right, but is still available to click if you move right enough times.

Neil mentioned that.  I calculated the widths and set the widths and divided the widths equally.  Probably used  a too high total pixel count.   But it appears that this version is not very popular and probably deserves no more attention.

EDIT: I found the problem..  I forgot to set {min,max}Width when setting up buttons.

**Comment by debmint** [comment]
> Oh right, I forgot about that PR. Yeah, I like the single options menu better than this.

Would you be in favor of just deleting this PR?

**Comment by TwitchBronBron** [comment]
> > Oh right, I forgot about that PR. Yeah, I like the single options menu better than this.
> 
> Would you be in favor of just deleting this PR?

Yes, I would be. But I think it's ultimately @neilsb 's call

**Pull request closed without merging**
