### PR TITLE
Set usePoster and ImageWidth against each HomeItem

### LINKED ISSUE #302: App Crash on Library Scan
When a Library is updated and you're watching a stream, when you exit the stream and go back to the Home Page. After the Home Page updates showing the new library content, the app will exit out to the Roku Main Menu, causing you to reopen the Jellyfin App.

### PR DESCRIPTION
**Pull request by neilsb**
**Changes**
* Set usePoster and ImageWidth against each HomeItem to avoid having to call `GetParent()` which may be null if the node is being reused

**Issues**
fixes #302

### CODE REVIEW

**Review by cewert — CHANGES_REQUESTED** [review]
Tested this and I'm seeing some of the blue background show up around the edges of the movie posters. Sent you an image on matrix

**Comment by cewert** [comment]
So after some more testing it's become clear that this PR is not causing my issue ( I still saw the blue borders when testing master). It was the older roku I used to test this PR:
Model - 3500X
Roku OS - 9.4.0

I still need to track down which PR caused my old roku to start displaying things differently but I'll make a new issue for that

**Review by cewert — APPROVED** [review]

**Review by cewert — APPROVED** [review]
Can't reproduce crash. Looks good to me

**Comment by neilsb** [comment]
> I still need to track down which PR caused my old roku to start displaying things differently but I'll make a new issue for that

I've not had time to test yet, but I'll bet it's #300 where the backdrop was changed from a Rectangle to an Image to let it have the same rounded corners as the actual posters.

**Pull request merged**
