### PR TITLE
Tips and Tricks draft.

### PR DESCRIPTION
**Pull request by jimdogx**
Initial cut at a draft of a Tips and Tricks page.  Not quite a User Guide, but more of a FAQ?

**Changes**
Adds a new markdown page with Tips and Tricks.  Also adds a new folder for any images needed for the Tips and Tricks page.

Is this something we even want???  Is someone that is better at writing guides interested in taking a stab at it?

**Edit**
Looking to make this an embedded help guide instead.  The markdown file could go on the official doc website (if we want one there and we clean it up).

### CODE REVIEW

**Comment by jimdogx** [comment]
@candry7731 Including you here since I'm pointing out your new Voice Search feature.

**Comment by crobibero** [comment]
This looks like something that would be a great fit for our docs website :-)

**Comment by jimdogx** [comment]
> This looks like something that would be a great fit for our docs website :-)

For some reason I thought the doc guide was all server side stuff.  Didn't realize there was a client section.  However, I'm now seeing if this is worthy of building in to the client itself.

**Comment by 1hitsong** [comment]
@jimdogx Based on the shift to using the client documentation. Shall we close this PR?

**Comment by candry7731** [comment]
I still think we need a user facing help section....

Even my wife didn't know she could use the voice seach on the guide and I
built the damn thing.....

**Comment by jimdogx** [comment]
With the advent of PR #916 and also the idea of just updating the Jellyfin client docs, I'm going to go ahead and close this PR.

**Pull request closed without merging**
