### PR TITLE
Select user on login and other login updates

### LINKED ISSUE #80: Display list of available users on Login screen
**Describe the feature you'd like**
Display a list of users, with their profile picture, at login screen. Prompt for password when user is selected

**Additional context**
An API call to /Users/Public provides a list of available users. If field "PrimaryImageTag" is not null, grab users profile picture. Otherwise show default image (web client uses /web/img/logindefault.png)

### LINKED ISSUE #136: Back Button Does Not Work During Sign-In
**Describe the bug**
During sign-in steps (or change server/user), the back button does not take you back to the previous activity.
For example, if you sign out, you go to the user sign-in screen. If you no longer have a valid account/can't log in (for whatever reason), you can't go back further to change the server. Another scenario would be entering the incorrect server during setup, and then not having a valid account to sign in with.

**To Reproduce**
1. Install the app (with clean config, you may need to restart Roku first), and launch
2. Enter a valid JF server (e.g. `https://demo.jellyfin.org/stable`)
3. Try to sign in with any account other than `demo` (no other public accounts exist)
4. Try to press back to change server, and it just stays on the same screen

**Expected behavior**
Pressing the back button should always take you to the previous activity or entry, failing that, taking you to the server select screen.

**Additional context**
This is to prepare for #122, specificially §4.7.

### PR DESCRIPTION
**Pull request by thomabx**
After the users enters the server's information, display a list of all publicly available users to select before requesting password entry.

Back now functions on all login screens. User can now go back from the password entry to the user selection, back from the user selection to the server entry, and from the server entry to the exit the program.

**Changes**
Add http:// or https:// on server entry
If no base URL is provided at server selection, adds default ports to the server URL

**Issues**
Fixes  #136, #80

### CODE REVIEW

**Review by cewert — COMMENTED** [review]
A couple things I noticed after a short test:

Signing out and in again seems to make the app exit if done a few times in a row. The number of times changed but the app would just close with no error eventually.

When hitting back on the user select screen, I'm taken back to the server URL screen as expected but the server URL was reset (even after a reboot). So if I sign out and then accidentally hit back I will have to re-enter my server details.
Possible solutions: save the server details and only replace them if textbox changes or add a button on user select screen to modify server details and then change back button to exit app

I saw a lot of variables names that started with a capital letter, was that intentional?

**Comment by thomabx** [comment]
> A couple things I noticed after a short test:
> 
> Signing out and in again seems to make the app exit if done a few times in a row. The number of times changed but the app would just close with no error eventually.

I was able to replicate this. After signing out, at any point if you press back while logging in the main loop will fire that back was pressed when it had focus. Checking if a scene currently exists and then unobserving back fixes this. LoginFlow is only called in one place and m.scene observes it right after.

> When hitting back on the user select screen, I'm taken back to the server URL screen as expected but the server URL was reset (even after a reboot). So if I sign out and then accidentally hit back I will have to re-enter my server details.
> Possible solutions: save the server details and only replace them if textbox changes or add a button on user select screen to modify server details and then change back button to exit app

~~Do we want the server details to persist while the program is running only or should they persist on reboot?~~

I updated it to persist through boots. On subsequent boots if there is server information it will take the user directly to user selection.

> I saw a lot of variables names that started with a capital letter, was that intentional?

I was using Pascal case for the variables from the conversation in #142 about the project's style. I have no preference either way. Should I change variables to camel case?

**Comment by thomabx** [comment]
I changed setting the selected user to be called on itemSelect. Using the OK key caused an issue when scrolling quickly through users and then pressing OK. If the animation was still moving when OK was pressed, it would return the value of the user highlighted at the start of the animation instead of the actual user selected.

**Comment by cewert** [comment]
@thomabx Yea I think we should change the vars to camelCase. That PR was just about component and file names. Currently we only use pascal case for components, file names, and (some)functions.

**Review by cewert — APPROVED** [review]
When selecting a user with a password I'm taken to a config scene with the username filled in. I hit back expecting to go back to the user select but instead it took me back to server URL screen.

Not a big deal since it's only one wasted click but thought I'd mention it.

Nice work on this!

**Pull request merged**
