### PR TITLE
Update npm dependencies, add bslint config, and fix CI errors

### LINKED ISSUE #617: Make CI throw error for unused code
Right now it's showing the build as passing for the [latest commit](https://github.com/jellyfin/jellyfin-roku/runs/6634184931?check_suite_focus=true) but there is a warning from bslint when running `npm run validate`

```
Run npm run validate
  npm run validate
  shell: /usr/bin/bash -e {0}

> jellyfin-roku@1.4.12 validate /home/runner/work/jellyfin-roku/jellyfin-roku
> npx bsc --copy-to-staging=false --create-package=false

[02:53:58:8500 AM]  Loading 1 plugins for cwd "/home/runner/work/jellyfin-roku/jellyfin-roku"
[02:53:58:8690 AM]  Parsing files
[02:53:59:9210 AM]  Parsing files finished. (2.378ms)
[02:53:59:9260 AM]  Validating project
[02:54:00:0260 AM]  Validating project finished. (99.530ms)

source/VideoPlayer.brs:136:17 - warning BSLINT1005: Variable 'group' is set but value is never used

 136                  group = CreateMovieDetailsGroup(m.episode_id)
 136                  ~~~~~     
```

### LINKED ISSUE #621: App (and roku) crashes when selecting TV library from Home screen
**Describe the bug**
Viewing any TV library from the home screen crashes the app hard. so bad that my roku locks up. no home button. nothing. I have to hard reset the roku by pulling the power. ~~So this might be happening on other libraries but~~ this is a PITA to test. also happening on Movie libraries

**To Reproduce**

1. load latest version of dev
2. open a tv library from home -> my media
3. observe

**Expected behavior**
Works with no crash

**Logs**
```
Invalid value for left-side of expression. (runtime error &he4) in pkg:/source/ShowScenes.brs(340)
Backtrace:
#1  Function createitemgrid(libraryitem As Dynamic) As Dynamic
   file/line: pkg:/source/ShowScenes.brs(341)
#0  Function main(args As Dynamic) As Void
   file/line: pkg:/source/Main.brs(111)
Local Variables:
libraryitem      roSGNode:HomeData refcnt=2
global           Interface:ifGlobal
m                roAssociativeArray refcnt=3 count:7
group            Invalid
Threads:
ID    Location                                Source Code
 0*   pkg:/source/ShowScenes.brs(340)         group.parentItem = libraryItem
 1    ...ents/Buttons/TextSizeTask.brs(7)     reg = CreateObject("roFontRegistry")
  *selected
```

**Screenshots**
crash-when-selecting-tv-library

**Additional context**
latest commit on dev

### PR DESCRIPTION
**Pull request by cewert**
Before updating, bslint spit out 1 warning. After updating, I'm seeing 45 errors and 2 warnings 😮 

```
components\Buttons\TextSizeTask.brs:21:1 - error BSLINT3017: Code style: File should end with a newline

 21  end sub
 __  ~~~~~~~


components\ItemGrid\Alpha.brs:28:1 - error BSLINT3017: Code style: File should end with a newline
 28  end function
 __  ~~~~~~~~~~~~


components\ItemGrid\FavoriteItemsTask.brs:15:1 - error BSLINT3017: Code style: File should end with a newline

 15  end sub
 __  ~~~~~~~


components\ItemGrid\ItemGridOptions.brs:150:5 - warning BSLINT1005: Variable 'error' is set but value is never used

 150      error = []
 ___      ~~~~~     


components\ItemGrid\ItemGridOptions.brs:257:1 - error BSLINT3017: Code style: File should end with a newline

 257  end function
 ___  ~~~~~~~~~~~~


components\ItemGrid\LoadItemsTask2.brs:95:1 - error BSLINT3017: Code style: File should end with 
a newline

 95  end sub
 __  ~~~~~~~


components\JFOverhang.brs:126:1 - error BSLINT3017: Code style: File should end with a newline   

 126  end sub
 ___  ~~~~~~~


components\JFScreen.brs:16:1 - error BSLINT3017: Code style: File should end with a newline      

 16  end sub
 __  ~~~~~~~


components\JFVideo.brs:61:19 - error BSLINT3014: Add comma after the expression

 61          "ItemId": m.top.id
 __                    ~~~~~~~~


components\JFVideo.brs:64:45 - error BSLINT3013: Remove optional comma

 64          "IsPaused": (m.top.state = "paused"),
 __                                              ~


components\PlaystateTask.brs:34:27 - error BSLINT3013: Remove optional comma

 34          "PositionTicks": 0,
 __                            ~


components\config\ConfigData.brs:2:1 - error BSLINT3017: Code style: File should end with a newline

 2  end sub
 _  ~~~~~~~


components\data\CollectionData.brs:36:1 - error BSLINT3017: Code style: File should end with a newline

 36  end sub
 __  ~~~~~~~


components\data\HomeData.brs:122:1 - error BSLINT3017: Code style: File should end with a newline
 122  end sub
 ___  ~~~~~~~


components\data\ImageData.brs:7:1 - error BSLINT3017: Code style: File should end with a newline 

 7  end sub
 _  ~~~~~~~


components\data\MovieData.brs:73:1 - error BSLINT3017: Code style: File should end with a newline
 73  end sub
 __  ~~~~~~~


components\data\OptionsButton.brs:5:1 - error BSLINT3017: Code style: File should end with a newline

 5  end sub
 _  ~~~~~~~


components\data\OptionsData.brs:38:1 - error BSLINT3017: Code style: File should end with a newline

 38  end sub
 __  ~~~~~~~


components\data\SceneManager.brs:232:1 - error BSLINT3017: Code style: File should end with a newline

 232  end sub
 ___  ~~~~~~~


components\data\SearchData.brs:15:1 - error BSLINT3017: Code style: File should end with a newline

 15  end sub
 __  ~~~~~~~


components\data\TVSeasonData.brs:18:1 - error BSLINT3017: Code style: File should end with a newline

 18  end sub
 __  ~~~~~~~


components\data\UserData.brs:33:42 - error BSLINT3013: Remove optional comma

 33              server: get_setting("server"),
 __                                           ~


components\data\UserData.brs:63:1 - error BSLINT3017: Code style: File should end with a newline 

 63  end sub
 __  ~~~~~~~


components\data\VideoData.brs:21:1 - error BSLINT3017: Code style: File should end with a newline
 21  end sub
 __  ~~~~~~~


components\home\Home.brs:12:1 - error BSLINT3017: Code style: File should end with a newline     

 12  end sub
 __  ~~~~~~~


components\home\HomeItem.brs:227:1 - error BSLINT3017: Code style: File should end with a newline
 227  end sub
 ___  ~~~~~~~


components\home\HomeRows.brs:915:1 - error BSLINT3017: Code style: File should end with a newline
 915  end function
 ___  ~~~~~~~~~~~~


components\liveTv\LoadChannelsTask.brs:10:43 - error BSLINT3013: Remove optional comma

 10          UserId: get_setting("active_user"),
 __                                            ~


components\liveTv\LoadProgramDetailsTask.brs:12:43 - error BSLINT3013: Remove optional comma     

 12          UserId: get_setting("active_user"),
 __                                            ~


components\liveTv\LoadProgramDetailsTask.brs:41:1 - error BSLINT3017: Code style: File should end with a newline

 41  end sub
 __  ~~~~~~~


components\liveTv\LoadSheduleTask.brs:12:23 - error BSLINT3014: Add comma after the expression   

 12          EnableImages: false
 __                        ~~~~~


components\liveTv\LoadSheduleTask.brs:14:25 - error BSLINT3014: Add comma after the expression   

 14          EnableUserData: false
 __                          ~~~~~


components\liveTv\LoadSheduleTask.brs:15:21 - error BSLINT3014: Add comma after the expression   

 15          channelIds: m.top.channelIds
 __                      ~~~~~~~~~~~~~~~~


components\movies\AudioTrackListItem.brs:33:1 - error BSLINT3017: Code style: File should end with a newline

 33  end sub
 __  ~~~~~~~


components\movies\VideoTrackListItem.brs:33:1 - error BSLINT3017: Code style: File should end with a newline

 33  end sub
 __  ~~~~~~~


components\photos\LoadPhotoTask.brs:9:24 - error BSLINT3014: Add comma after the expression      

 9              maxHeight: 1080
 _                         ~~~~


components\screensaver\Screensaver.brs:11:1 - error BSLINT3017: Code style: File should end with 
a newline

 11  end sub
 __  ~~~~~~~


components\search\SearchResults.brs:3:1 - error BSLINT3017: Code style: File should end with a newline

 3  end sub
 _  ~~~~~~~


components\settings\settings.brs:141:1 - error BSLINT3017: Code style: File should end with a newline

 141  end function
 ___  ~~~~~~~~~~~~


source\VideoPlayer.brs:136:17 - warning BSLINT1005: Variable 'group' is set but value is never used

 136                  group = CreateMovieDetailsGroup(m.episode_id)
 ___                  ~~~~~


source\api\Items.brs:49:29 - error BSLINT3014: Add comma after the expression

 49          "IncludeItemTypes": "TvChannel,Movie,BoxSet,Series,Episode,Video"
 __                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


source\api\constants.brs:20:35 - error BSLINT3014: Add comma after the expression

 20                  descending_white: "pkg:/images/icons/down_white.png"
 __                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


source\api\constants.brs:31:1 - error BSLINT3017: Code style: File should end with a newline     

 31  end sub
 __  ~~~~~~~


source\utils\Subtitles.brs:202:31 - error BSLINT3014: Add comma after the expression

 202                  "IsExternal": stream.IsExternal
 ___                                ~~~~~~~~~~~~~~~~~


source\utils\deviceCapabilities.brs:92:37 - error BSLINT3014: Add comma after the expression     

 92                  "MaxAudioChannels": StrI(maxAudioChannels) ' Currently Jellyfin server expects this as a string
 __                                      ~~~~~~~~~~~~~~~~~~~~~~



source\utils\deviceCapabilities.brs:114:34 - error BSLINT3014: Add comma after the expression    

 114                          "Value": StrI(maxAudioChannels) ' Currently Jellyfin server expects this as a string
 ___                                   ~~~~~~~~~~~~~~~~~~~~~~



source\utils\deviceCapabilities.brs:253:28 - error BSLINT3013: Remove optional comma

 253              "Type": "Audio",
 ___                             ~

[01:14:40:6830 PM]  Found 45 errors
```

**Changes**
Updated all npm devDependencies to latest version
npm install + npm audit fix (went from 17 to 13 vulnerabilities)
Add a `bslint.json` file so that unused variables will trigger as errors instead of warnings

**Issues**
Fixes #617
Fixes #621 (needed to fix so we could continue testing this PR)

### CODE REVIEW

**Comment by cewert** [comment]
We need dependabot or something to help us keep these updated in the future. Our CI depends on them

**Comment by cewert** [comment]
I've also added a `bslint.json` file so that unused variables will trigger as errors instead of warnings. We had a couple that went unnoticed. The default behavior was to warn instead of error.

Here's the defaults for [bslint](https://github.com/rokucommunity/bslint#rules) if you're curious

```
{
    "rules": {
        "inline-if-style": "then",
        "block-if-style": "no-then",
        "condition-style": "no-group",
        "named-function-style": "auto",
        "anon-function-style": "auto",
        "aa-comma-style": "no-dangling",
        "no-print": "off",
        "no-todo": "off",
        "todo-pattern": "TODO|todo|FIXME",
        "no-stop": "warn",

        "type-annotations": "off",

        "assign-all-paths": "error",
        "unsafe-path-loop": "error",
        "unsafe-iterators": "error",
        "unreachable-code": "info",
        "case-sensitivity": "warn",
        "unused-variable": "warn",
        "consistent-return": "error"
    }
}
```

**Review by TwitchBronBron — APPROVED** [review]
Looks great!

**Comment by cewert** [comment]
So I have almost all of the errors fixed. The majority were missing a new line at end of file, missing commas in asoc. arrays, and unneeded commas at the end of asoc. arrays.

I fixed one of the unused code errors:
```
components/ItemGrid/ItemGridOptions.brs:150:5 - error BSLINT1005: Variable 'error' is set but value is never used

 150      error = []
```
I removed the try catch at first but realized it's probably needed for the last row in the list when there's no guarantee the row is full.

The second unused code, and last error, I'm having trouble wrapping my head around and could use some help figuring out. @neilsb @jimdogx 
```
source/VideoPlayer.brs:136:17 - error BSLINT1005: Variable 'group' is set but value is never used

 136                  group = CreateMovieDetailsGroup(m.episode_id)
```

**Comment by jimdogx** [comment]
> The second unused code, and last error, I'm having trouble wrapping my head around and could use some help figuring out. @neilsb @jimdogx

```
source/VideoPlayer.brs:136:17 - error BSLINT1005: Variable 'group' is set but value is never used

 136                  group = CreateMovieDetailsGroup(m.episode_id)
```
Far as I can tell, group really isn't used.  I removed all of the group variables not used in that block (there is one group variable that is used).  Of course I can't test it because of the hard crash you just pointed out in #621

**Comment by cewert** [comment]
@jimdogx I pushed a fix for #621. You should be good to test your fix now

**Comment by jimdogx** [comment]
As far as I can tell with my small little test server, removing those unused group variables didn't change anything.  Let me know if you want me to push my changes.

**Comment by cewert** [comment]
> Let me know if you want me to push my changes.

Yes, please!

**Comment by cewert** [comment]
So `npm run validate` passes but now `npm run check-formatting` is throwing an error. Doesnt give a line just a file

```
Checking formatting...
/home/runner/work/jellyfin-roku/jellyfin-roku/components/ItemGrid/ItemGridOptions.brs
Formatting issues found in the above file(s)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! jellyfin-roku@1.4.12 check-formatting: `npx bsfmt --check`
npm ERR! Exit status 1
```

**Comment by cewert** [comment]
I ran `npx bsfmt --write` and that cleared it up. It was from me adding back the try catch statement 🤡 

Still need to test jimdogs changes

**Comment by cewert** [comment]
The unused group variables came from #557 so I selected TV episodes from the "continue watching" home row, and tested all the options and everything worked as expected.

I think this is ready to merge. What do you guys think? @jimdogx @neilsb 

PS: Found a new bug while I was testing this 😞 #624

**Comment by jimdogx** [comment]
LGTM

**Review by neilsb — APPROVED** [review]

**Pull request merged**
