### PR TITLE
Remember subtitle selection

### LINKED ISSUE #547: When resuming playback of a video, subtitles don't work.
**Describe the bug**

When starting a video with subtitles, they work as expected.

When pausing that video, going back to the video later and resuming from that same spot, subtitles no longer work. You can get them to work by, instead of using the "Resume from X:X" option, choose the "Start from beginning" and fast forwarding to the spot you were in the video.

**To Reproduce**

See above.

**Expected behavior**

Subtitles should work when resuming a video.

**Logs**

N/A.

**Screenshots**

N/A

### PR DESCRIPTION
**Pull request by jimdogx**
Remembers the user's last selected subtitle selection (language) and continues to use it (if found) for other media until the users turns off subtitles (by selecting None).

**Changes**
Only side affect of this change is I had to make subtitle selection **_during playback_** always stop/start the media.

**Issues**
Fixes: #547 

This is more of a "global" subtitles on / off.  Not sure if this is desirable.

I tested by switching back and forth between two movies and changing the subtitle selection.  When switching to another movie, subtitles remained on and in the correct language.  When I turned subtitles off (None), they remained off even after switching to another movie.

### CODE REVIEW

**Comment by neilsb** [comment]
> This is more of a "global" subtitles on / off. Not sure if this is desirable.

That's what [Roku suggest](https://developer.roku.com/en-ca/docs/developer-program/media-playback/closed-caption.md#custom-control-settings), so I think that's fine (and what I thought the app was actually doing.

**Comment by crobibero** [comment]
What is the experience if media has more then one subtitle track in the desired language?

Eg: normal subtitle track, commentary track

**Comment by jimdogx** [comment]
> What is the experience if media has more then one subtitle track in the desired language?
> 
> Eg: normal subtitle track, commentary track

It's not very smart.  It uses the first one it finds.  It will definitely address the use case in #547 (resuming the same video), but it is more of a sledgehammer approach which is why I wasn't sure if it was the desired approach.

**Comment by whiteowl3** [comment]
the app is not ready for the subtitle selection to persist until the user has the option to drop graphical subs, OR select subs prior to playback.  selecting graphical subtitles on the roku can cause playback failures due to the roku's hard 20 second timeout. if it takes the server more than 20 seconds to respond with the transcode,  and those subtitles are reselected on playback, its conceivable that playback would be permanently broken until the setting was somehow flushed.
the behavior of reverting to NO subtitles on every playback is the only thing that protects us from this right now.

**Comment by jimdogx** [comment]
> selecting graphical subtitles on the roku can cause playback failures due to the roku's hard 20 second timeout.

Oh wow...this is good to know.

> OR select subs prior to playback. 

When the selection is persisted, the subs are technically selected prior to playback.  But I might not be understanding.

> the behavior of reverting to NO subtitles on every playback is the only thing that protects us from this right now.

Sounds like we might need to drop this PR.  Any chance you have an example of a "graphical sub"... I'm not a subtitle expert by any means, so I'd love to learn more about the differences.

**Comment by crobibero** [comment]
> Any chance you have an example of a "graphical sub"

I'm also no expert on subtitle formats, but I believe graphical subtitles typically refer to ASS / SSA formats. The only place I've seen that format is on anime. 

I could be totally wrong though

**Comment by jimdogx** [comment]
@whiteowl3 I see what you're saying now.  Once I selected subs on an Anime show I got the "Error cannot retrieve".  At that point, I could no longer watch the Anime show until I went to a different movie (that did not have graphical subs) and played it so that I could select "None".

Question: I currently stop persisting anything once a user selects "None".  What if I also stopped persisting the user selection anytime there was a playback error?

**Comment by neilsb** [comment]
> Sounds like we might need to drop this PR. Any chance you have an example of a "graphical sub"... I'm not a subtitle expert by any means, so I'd love to learn more about the differences.

ASS Subtitles are just a text file, but have additional formatting information on them such as font family, size, colour, etc.  They are just burnt in by the server since Roku can't handle them.  It's fairly straightforward to convert srt subtitles to ass, [this tool](https://www.better-converter.com/Subtitles-Converter/Str-to-Ass-Subtitle-Converter) is what I use for testing, and once you have the file it's pretty easy to edit for testing.

**Comment by neilsb** [comment]
> playback would be permanently broken until the setting was somehow flushed.

I think as long as we respect the Roku global setting for subtitles as Roku suggest, then we should be OK.

i.e.  
 - When a user enables subtitles from Jellyfin, the Roku Global Subtitle option is set to ON
 - When a user disables subtitles from Jellyfin, the Roku Global Subtitle option is set to OFF
 - When a user start playback of a piece of media, we check the Roku Global Subtitle option and choose whether to display or not based on the value

I guess it's just really using the device setting to persist the caption mode, rather than having a setting in the jellyfin app itself  (although having other settings to store the selected language etc is obviously fine).

**Comment by whiteowl3** [comment]
the issue for me is dvdsub. they are *everywhere* in the wild, and are also what the home user will produce when they rip their dvds. no roku device supports them to my knowledge. I think the appropriate way to handle them is to expose a setting as already discussed in #550 to allow the user to make the decision based on their server power, but when all is said and done I'm happy as long as changes don't cause an obnoxious failure loop if the server fails to transcode within the timeout.

**Comment by jimdogx** [comment]
> whiteowl3
> I'm happy as long as changes don't cause an obnoxious failure loop if the server fails to transcode within the timeout.

The current version of this PR shouldn't make anything worst.  For those not using SSA/ASS they will have subtitles persisted until they select "None".  For a user using SSA/ASS and receiving an error, this will not change their experience.  They will get the error and the saved subtitle will be deleted.  At that point, they're right back where they'd be before any changes from this PR.

> neilsb
> I guess it's just really using the device setting to persist the caption mode

Should we move forward with this as is?  Or abandon ship and re-write subtitle handling to observe globalCaptionMode instead?

**Comment by neilsb** [comment]
> Should we move forward with this as is? Or abandon ship and re-write subtitle handling to observe globalCaptionMode instead?

I think we're fine to go ahead with this.  I'll try and get it tested over the weekend.

**Comment by neilsb** [comment]
I consistently get a crash when media is started and subtitles are displayed automatically, then pressing down and selecting "None".  It crashes to subtitles.brs line 87.   

> 'Dot' Operator attempted with invalid BrightScript Component or interface reference.

It doesn't happen if the media is started with no subtitles, you turn on subtitles then turn them off again.

It also doesn't happen if media is started with subtitles, you select a different language, then select none.

Only appears to happen when the first action you perform is changing the subtitles to none.

**Comment by jimdogx** [comment]
Thanks @neilsb!  Been testing other PRs and not my own haa haa.

One of which is #566 ... I wasn't sure if that PR would supersede this one.  But I'll test / fix this one when I have some time just in case or until told otherwise 😄

**Comment by jimdogx** [comment]
Closing this PR until we can come up with a better way to handle this issue.

**Pull request closed without merging**
