### PR TITLE
Play Song as Part of a Playlist

### PR DESCRIPTION
**Pull request by michaelcresswell**
## Changes
When user clicks on a song, queue the playlist and start playback at requested song.

Based on https://github.com/jellyfin/jellyfin-roku/pull/1644

## Issues
https://github.com/jellyfin/jellyfin-roku/issues/1894

### CODE REVIEW

**Comment by michaelcresswell** [comment]
There are a few other instances of a single song being queued from what may be a list but I'm not sure where they're called from so I hesitate to change to either.

https://github.com/jellyfin/jellyfin-roku/blob/master/source/Main.bs#L393

https://github.com/jellyfin/jellyfin-roku/blob/master/source/Main.bs#L559

**Comment by cewert** [comment]
Line 393 is when a single audio file is selected from the home screen. I know the favorites row supports single songs but I'm not sure if there are more rows with support as well

Line 559 is from the search results

**Comment by cewert** [comment]
One idea for the single songs would be to open the album the song comes from (do all songs in jellyfin have an album?) with the single song selected. That way the user could learn about the album before choosing to play it which would then play the whole album. Or you could just assume the user wants to listen to the album and queue the whole album but IMO that would make more sense for quickplay (the play button).

**Comment by michaelcresswell** [comment]
The enhancements make sense but they sound more involved than queueing up the rest of a list so I think they should be separate tasks. Especially while I’m just getting started with the codebase.

**Comment by cewert** [comment]
> The enhancements make sense but they sound more involved than queueing up the rest of a list so I think they should be separate tasks. Especially while I’m just getting started with the codebase.

Of course! I didn't mean to imply you needed to change anything :)

**Review by cewert — APPROVED** [review]

**Pull request merged**
