### PR TITLE
Alpha left

### PR DESCRIPTION
**Pull request by candry7731**
Move Alpha Picker to the Left side of the screen

### CODE REVIEW

**Comment by candry7731** [comment]
I don't know why all these other files are included in the PR..... they should not be as they were included in other pr's.... How do I fix this?

**Comment by jimdogx** [comment]
Not really sure what you did, but if this is to move the Alpha Picker to the other side of the screen (and assuming that's a relatively small change), I'd close / delete this PR and branch..... make sure you fetch / pull from Master and create a fresh branch and then make your changes.

**Comment by crobibero** [comment]
When I create PRs I base my branch off of upstream/master, where upstream is the Jellyfin repo attached as a remote

**Comment by candry7731** [comment]
Thanks Guys! I got finally got it, hopefully....lol

**Pull request closed without merging**
