### PR TITLE
Made work around for jellyfin#93

### PR DESCRIPTION
**Pull request by TheLastMelon**
When passwords would include ampersand '&', they wouldn't process correctly with URL encoding.

**Changes**
Replaces '&' with '%26'

**Issues**
Fixes issue #93

### CODE REVIEW

**Comment by bisby** [comment]
I'm sure this specific urlencoding isnt the only one we actually need.

https://developer.roku.com/docs/references/brightscript/interfaces/ifurltransfer.md#escapetext-as-string-as-string

There's already a utility to do it for you.

**Comment by bisby** [comment]
Also would have accepted an updated PR.

**Comment by TheLastMelon** [comment]
My bad, first time contributing on github. I was under the impression had to close an open a new one.

**Comment by bisby** [comment]
Thanks for contributing!

Pretty sure you can just push updates to your branch and the PR updates to reflect that...
At least it does for branch based PRs. Fork based PRs and open source is a bit new for me too.

Either way, thanks!

**Comment by TheLastMelon** [comment]
Yeah, I reopened without testing first. Seems like Escape() broke it even more.

**Comment by bisby** [comment]
`Escape` itself isnt in the global namespace. So you'll need to have a `roUrlTransfer` object handy, and `transfer_object.Escape(password)`

BrightScript doesn't always make it easy.

Feel free to leave the PR open and just push up new updates as you work through the issues. and then let us know when it's ready for us to test.

**Comment by TheLastMelon** [comment]
Yeah, I jumped head first into brightscript. Should have done a little more reading about it. Appreciate your patience.

**Comment by anthonylavado** [comment]
@TheLastMelon As mentioned, let us know when you want us to take another look at this 🙂

**Comment by TheLastMelon** [comment]
I think it’s ready 🤞

**Review by bisby — APPROVED** [review]
Auth still works for me, so at the very least this didn't regress anything.

**Pull request merged**
