### PR TITLE
Enable brighterscript, create NPM build scripts, install and use roku-log, and use bsc import statements

### PR DESCRIPTION
**Pull request by cewert**
There's a lot going on in this PR, sorry 😆 Everything kind of ties together. The downside to using [brighterscript](https://github.com/rokucommunity/brighterscript) for our app is that all the files need to be compiled into normal brightscript code before the app can run. This will make using the dev build and testing things take a bit longer since we will need to wait for the app to be built before we can launch the debugger.

## Changes
- Install [roku-log](https://github.com/georgejecook/roku-log) and convert all current print statements
  - Now we can log all the things to make debugging the dev version of the app easier. All logging and comments are removed during the new production workflow (`npm run build-prod`)
  - NOTE: logger only works in `components/`
- Enable [brighterscript](https://github.com/rokucommunity/brighterscript) using the `"allowBrighterScriptInBrightScript": true` flag when compiling
  - This allows us to use brighterscript(bsc) in our normal .brs files and also prevents us from having to rename all files from .brs to .bs which would screw up git history for all files. If we ever want our files to be .bs we will have to do this one day but this PR isn't forcing the issue. If that's what we want I'd be happy to add that in.
  - This is what led me to build the NPM build scripts - so that we could use bsc code and have it compiled to normal .brs code before we launch or channel for testing
- Create NPM build scripts
  - `npm run build` (uses `bsconfig.json`)- build the dev version of the app with dev logos, *all* translation files, enable logging with roku-log, enable clickable log entries etc.
  - `npm run build-prod` (uses `bsconfig-prod.json`)- build the production version of the app with proper logos, only the translation files that roku supports, remove all logging and print statements, remove clickable log entries etc.
- Force all files to use [`import` statements](https://github.com/rokucommunity/brighterscript/blob/master/docs/imports.md) for dependencies

### CODE REVIEW

**Comment by cewert** [comment]
Still need to:

- [x] Finish converting current print statements
- [x] Fix `npm run check-formatting` errors
- [x] Update build workflows to use NPM scripts instead of the Makefile

**Comment by cewert** [comment]
Going to stop fixing merge conflicts due to dependency updates until this is reviewed/approved.

**Comment by cewert** [comment]
I've fixed all the merge conflicts from merging #1141. After some testing everything seems to be working and this is ready for review again.

**Comment by 1hitsong** [comment]
There are  a dozen or so print statements still in the code. Is the goal to convert them all?

image

**Comment by cewert** [comment]
> There are a dozen or so print statements still in the code. Is the goal to convert them all?

Yes, but the logger doesn't work in `Main.brs` and I have yet to get it working for the files in `source/` - currently it only works for files in `components/`.

I believe I can get this working by converting the code in `source/` to use brighterscript classes like the [docs show](https://github.com/georgejecook/roku-log/blob/master/docs/Registering-loggers-and-logging.md) but I haven't tried it yet. This PR was way too big already 😆

Edit: I [made an issue](https://github.com/jellyfin/jellyfin-roku/issues/1245) to track adding roku-log to the source/ folder

**Review by 1hitsong — APPROVED** [review]

**Pull request merged**
