### PR TITLE
Add Genres, Parental Ratings, and Years as Movie Filters

### PR DESCRIPTION
**Pull request by 1hitsong**
**Changes**
Adds Genres, Parental Ratings, and Years as filters for movies.

Currently you can only select 1 filter at a time, but you can selected multiple values for that filter. A followup PR can add the ability to select multiple filters.

Demo: https://social.linux.pizza/@tgpo/109587441382119771

image

### CODE REVIEW

**Comment by jimdogx** [comment]
@1hitsong if you resolve the conflicts I'll re-test this with the latest unstable branch 👍

**Comment by jimdogx** [comment]
Something weird is happening with the view, but I don't know if it's related to this PR.

If I filter by a Genre (which works great), when I start to scroll down through the movies, as soon as it needs to load the next set (spinner is shown), it takes you back to the top of the movie list.

**Comment by 1hitsong** [comment]
@jimdogx Is this behavior happening in the release client?

**Comment by 1hitsong** [comment]
I was able to recreate this. I'll look int it.

**Comment by 1hitsong** [comment]
@jimdogx Should be fixed now.

**Comment by candry7731** [comment]
When I set a genre for the first time inside a movie folder it does not save or load the genre I selected. However on the second try it does save the genre and filter by the selected genre. 

https://user-images.githubusercontent.com/83685828/216879012-2c8f9bd1-9d0b-4fd2-8af1-151c216f9a43.mp4

**Comment by sevenrats** [comment]
> When I set a genre for the first time inside a movie folder it does not save or load the genre I selected. However on the second try it does save the genre and filter by the selected genre.
> 
>  Win.20230205.21.40.11.Pro.mp4

I am experiencing this issue as well.
It also seems strange that the filters persist through restarting the app.  It makes sense for the views to persist imho, but not the filters.
It would be great if there was a better solution for the year picker.

**Comment by 1hitsong** [comment]
@candry7731 I'm trying as many different ways as I can, but I can't recreate this issue. I'll keep at it.

@sevenrats 
> It also seems strange that the filters persist through restarting the app. It makes sense for the views to persist imho, but not the filters.

I can't say I've thought about it all that much. This is the existing functionality though. I can guarantee someone would get mad if we changed how it worked now.

> It would be great if there was a better solution for the year picker.

I'm open to ideas, but I figure this works fine for s first release.

**Review by jimdogx — APPROVED** [review]
Regarding what @sevenrats said, the persisting doesn't bother me however I am wondering if there should be some indication that things are filtered.  For example, when filtering TV shows it states at the top what it's filtered by.

**Comment by 1hitsong** [comment]
> Regarding what @sevenrats said, the persisting doesn't bother me however I am wondering if there should be some indication that things are filtered. For example, when filtering TV shows it states at the top what it's filtered by.

Eventually, I'd like to get to the point that you can apply multiple filters from various categories. Perhaps we can simply indicate the results are filtered and the user can open the filter menu to see what all is applied?

Or some kind of mini-info block that tells what the filters are?

I'll give this some thought and have a followup PR.

**Pull request merged**
