### PR TITLE
demonstrate fake blurhash

### PR DESCRIPTION
**Pull request by sevenrats**
This is a basic example to demonstrate the fake-blurhash decoding algorithm on roku.

the result looks really nothing like a traditional decode, but they are very similar to the source image and, in my opinion, have their own interesting beauty.

This fork just replaces all the posters in a Movies or Series type library with blurhash renders, to demonstrate that the method is fast enough.

I don't have the know-how to implement the double-buffering and what-not that would be required to fully implement this in jellyfin-roku, but I went ahead and packaged the fake-blurhash as an npm package, so anytime somebody wants to take a swing at it they can.

### CODE REVIEW

**Comment by neilsb** [comment]
That's really interesting.  It _should_ be straightforward to use instead of the blue background in the grid.  The blue is currently a poster that is displayed over the top of the main image until the image loaded signal is received, at which point it's hidden.  Therefore, in `GridItem.brs` if the `m.backdrop.uri` is set to the blurhash image it should use that instead of the blue, then hide when the main poster image is ready to display.

Would either need make sure that the `m.top.itemContent` either had the Poster blurhash string in it and call the blurhash function in `GridItem.brs`, or leave it where you have it in the but instead of setting the `m.top.posterURL` create a new property such as `m.top.PosterBlurhashUrl` in the `MovieDetails` object (etc) and use that.  

Would need to put some thought on into when best to generate the blurhash image.  e.g.  Where it is currently - so it will generate the file as soon as the item is loaded, even if it's not used,  or in the `GridItem.brs` file, where it would only generate it when it was being used - but may result in a delay??

**Comment by neilsb** [comment]
Quick update to use the blurhash image instead of the blue background.

Just to be clear, not suggesting this is the best way to do this.  Just adding it so the demonstration works with replacing the blurhash image with the actual poster.

**Comment by sevenrats** [comment]
```BrightScript Micro Debugger.
Enter any BrightScript statement, debug commands, or HELP.

Suspending threads...
Thread selected:  1*   ...omponents/data/SeriesData.brs(37)    bh = m.top.json.ImageBlurHashes.Primary[m.top.json.ImageTags

Current Function:
029:      if m.top.image <> invalid
030:          m.top.posterURL = m.top.image.url
031:      else
032:  
033:          if m.top.json.ImageTags.Primary <> invalid
034:  
035:              imgParams = { "maxHeight": 440, "maxWidth": 295 }
036:              m.top.posterURL = ImageURL(m.top.json.id, "Primary", imgParams)
037:*             bh = m.top.json.ImageBlurHashes.Primary[m.top.json.ImageTags.Primary]
038:              m.top.posterBlurHashUrl = fakeblurhash_renderBlurhash(bh, imgParams.maxWidth, imgParams.maxHeight)
039:          else if m.top.json.BackdropImageTags <> invalid
040:              imgParams = { "maxHeight": 440 }
041:              m.top.posterURL = ImageURL(m.top.json.id, "Backdrop", imgParams)
Source Digest(s): 
pkg: dev 1.5.0 b714643c43caa0ac5724c6368579d602 Jellyfin

Array operation attempted on variable not DIM'd. (runtime error &he7) in pkg:/components/data/SeriesData.brs(37)
Backtrace:
#1  Function setposter() As Void
   file/line: pkg:/components/data/SeriesData.brs(37)
#0  Function setfields() As Void
   file/line: pkg:/components/data/SeriesData.brs(25)
Local Variables:
global           Interface:ifGlobal
m                roAssociativeArray refcnt=3 count:2
imgparams        roAssociativeArray refcnt=1 count:3
bh               <uninitialized>
Threads:
ID    Location                                Source Code
 0    pkg:/source/Main.brs(83)                msg = wait(0, m.port)
 1    ...ponents/ItemGrid/ItemGrid.brs(495)   if m.swapAnimation.state = "stopped"
 2*   ...omponents/data/SeriesData.brs(37)    bh = m.top.json.ImageBlurHashes.Primary[m.top.json.ImageTags
  *selected```

**Comment by sevenrats** [comment]
I'm switching  this to  "ready" so that people don't shy away from testing.  The implementation is incomplete, in that only the movie and series posters within library views actually use the blurhash renders, but there are bugs that need to be sorted before full implementation is even reasonable. Please test and help me sort the crashes!

**Comment by sevenrats** [comment]
https://stackoverflow.com/questions/73460470/cannot-read-property-fetchspec-of-undefined-getting-this-error-when-doing-np

**Comment by sevenrats** [comment]
not stale

**Pull request closed without merging**
