### PR TITLE
Search redesign

### PR DESCRIPTION
**Pull request by candry7731**
Redesign the search scene
Add observer field to update items based on key press

**Changes**
1. Added Mini Keyboard
2. Moved to the left most side 

**Issues**
1. Need to add logic for observer field in the searchbox.brs
2. Add searchrow layout or grid layout to update itmes when keys are pressed

### CODE REVIEW

**Comment by jimdogx** [comment]
Pushed some updates.  Make sure to read the "TODO/FIXME" comments I sprinkled throughout 😄

**Comment by TwitchBronBron** [comment]
Looking good so far! This is a much needed enhancement to the app. A few suggestions:

1. don't focus the first search result after typing. The focus should stay on the keyboard all the time, unless the user manually leaves the text box by pressing right enough times. 

    https://user-images.githubusercontent.com/2544493/166675413-af9dcb1d-c7e0-4e33-8f7c-0809bbfb0817.mp4


2. Don't show the loading spinner on screen load. We should only be showing it when actually loading. Perhaps show some text  there instead, like "Start typing to instantly see search results" or even just "No results found". 

3. For episodes, I don't know what show they belong to. 
image

I wonder if we would be better served showing the results in a single-column vertical scrolling list (like the [MarkupList](https://developer.roku.com/docs/references/scenegraph/list-and-grid-nodes/markuplist.md)) rather than groups of results by category. This would allow the screen to fully utilize the horizontal space, but at the cost of showing less results on the screen at a time.

**Comment by candry7731** [comment]
> Looking good so far! This is a much needed enhancement to the app. A few suggestions:
> 
> 1. don't focus the first search result after typing. The focus should stay on the keyboard all the time, unless the user manually leaves the text box by pressing right enough times.
>    
>      
>        
>        
>    
>        jellyfin-search.mp4
> 2. Don't show the loading spinner on screen load. We should only be showing it when actually loading. Perhaps show some text  there instead, like "Start typing to instantly see search results" or even just "No results found".
> 3. For episodes, I don't know what show they belong to.
>    image
> 
> I wonder if we would be better served showing the results in a single-column vertical scrolling list (like the [MarkupList](https://developer.roku.com/docs/references/scenegraph/list-and-grid-nodes/markuplist.md)) rather than groups of results by category. This would allow the screen to fully utilize the horizontal space, but at the cost of showing less results on the screen at a time.

**Comment by candry7731** [comment]
@TwitchBronBron Thanks for the suggestions! 

1. Focus will stay on the keyboard, trying to work out the best logic for that
2. I like the "no results found" text... 
3. maybe adding a show title above the episode name or adding the show name above the image and the episode name below the image?
The web app show the show name above the episode name
image

5. I will also try to add voice search option to the keyboard, Do you have a voice remote?

**Comment by candry7731** [comment]
@TwitchBronBron Posted an update. let me know what you think. 

1. Added Series name above the episode poster
2. Fixed focus to stay on keyboard until user presses left to focus on search results
3. Updated search url to search the "Search/Hints" api
4. Updated to search function to search the entire letter string instead of waiting until it times out to update the letter string

TODO
1. Add animation to the keyboard to slide on and off screen when focus changes between keyboard and search results
2. update search url to search each "type" and have no limits as you are searching the entire search term and that should auto filter/limit the results

**Comment by candry7731** [comment]
How do I change this from a draft to a normal pr?

**Comment by jimdogx** [comment]
image

**Comment by tremby** [comment]
I came across this ticket whole searching for whether voice search support is in progress or planned.

> I will also try to add voice search option to the keyboard, Do you have a voice remote?

Did support for that make it into this changeset? It would be a massively welcome feature!

**Comment by neilsb** [comment]
@candry7731 Just changing from using the `MiniKeyboard` to the `DynamicMiniKeyboard` component should give you the voice search automatically.   It has an inbuild textbox, so looks like you may have to make some other small changes, but it should be fairly straightforward.

**Comment by candry7731** [comment]
Yes, ill try to get the updated tonight. And also work on the other episode, series pr to kot show for movies.

**Comment by candry7731** [comment]
Let me know if you guys can use the voice search.

**Comment by neilsb** [comment]
> Let me know if you guys can use the voice search.

Yup - voice search works with that change

**Comment by candry7731** [comment]
> > Let me know if you guys can use the voice search.
> 
> Yup - voice search works with that change

THAT'S AWESOME! I'm going to have to get a voice roku player.... lol

Now, It looks like there is not logic for "Parental Content"

**Comment by candry7731** [comment]
This has been updated/Replaced by #593

**Pull request closed without merging**
