### PR TITLE
Disable options button and overhang text as needed

### PR DESCRIPTION
**Pull request by cewert**
Disables options for screens that don't have any and prevents crashing. I think I got them all this time...

**Changes**
Disables options on:
config scene (server select and manual login)
sign out (change server)

### CODE REVIEW

**Comment by neilsb** [comment]
At the moment the option in TV Shows is just showing a blank box, so that can probably be disabled too?

And for the Movies screen, while it shows Sort Field and Sort Order, they're not editable at the moment.  Possibly want to disable it there too?

**Comment by cewert** [comment]
Yea good point. Collections too. Those are the only 3 pages besides the home page that ever had options i believe. I guess I left them in there because they don't cause the app to crash but yea they don't work. Ever since the single scene rewrite I think

**Review by neilsb — APPROVED** [review]
👍

**Comment by anthonylavado** [comment]
I'm okay to push this through, but we should either:
- disable it in the Movie screen now, or
- create an issue to remember to do that

We should also update whatever issue we have (if any) to remember to fix this later.

**Comment by neilsb** [comment]
Think it's already caught in those 2 specific screens by #147.

**Pull request merged**
