### PR TITLE
Add progress bar to pause menu

### PR DESCRIPTION
**Pull request by 1hitsong**
## Changes
Adds a progress bar indicator to the pause menu showing the user their current position, time left in the video, and a visual percentage bar.

## Demo
https://github.com/jellyfin/jellyfin-roku/assets/3330318/afd0db32-2210-4f3a-8118-dbe409858043

### CODE REVIEW

**Review by jimdogx — APPROVED** [review]
This is working for me 👍

**Review by cewert — COMMENTED** [review]
Works well. Timestamps and visuals are correct and I can't break it.

The only thing I don't like about the new bar is that the timestamps in the pause menu are smaller and in a different place than the ones in the rewind/ff trickplay bar. I know we were wanting them to look different so the user knows the pause menu bar isn't selectable but I found it a little jarring switching between the two menus because of this.

This is a bug I just found unrelated to this PR but it shows the two UIs next to each other:
PXL_20231112_034315849

to reproduce, hit left/right/rewind/ff while a video is playing then hit up or down and the pause menu will show up

**Comment by 1hitsong** [comment]
Styles slightly updated to match trickplay bar. Double bar bug fixed.

**Review by cewert — COMMENTED** [review]
Latest commit lines up the progress bar with the trickplay bar and fixes the bug as advertised.

The only thing I noticed is that the trickplay bar uses leading zeros for the timestamps but our pause menu doesn't. We should probably make those match if it's not too much trouble.

**Comment by 1hitsong** [comment]
Leading minutes added.

**Review by cewert — APPROVED** [review]

**Pull request merged**
