### PR TITLE
Fixes/jf video details wrong

### LINKED ISSUE #851: Subtitle Information is Displayed in Video Info Section If External SRT Files Are Present
Bug: If SRT subtitle files are present in a movie folder, subtitle info is displayed where the video codec/resolution info should be.

**To Reproduce**
1) Place an SRT file in a movie directory. 
2) See subtitle info displayed in place of video codec info
3) Don't have SRT file in the movie directory and correct codec information is displayed.

Client: Latest official / whiteowl HEVC direct play PR via dev channel
Server: 10.8.7

**Expected behavior**
Video codec and resolution information should be displayed in the video line of the movie details view.

IMG_20221117_191646726
IMG_20221117_194822548

### PR DESCRIPTION
**Pull request by jimdogx**
Iterate through video streams and make sure the codec we're displaying is an actual video codec (as opposed to "SUB-External Rip").

**Issues**
Fixes #851

### CODE REVIEW

**Comment by lakerssuperman** [comment]
Tried this PR with about 30 films in my library.  A mix of 1080p and 4K.  All reported the correct codec and resolution info!!

**Comment by 1hitsong** [comment]
I'm unable to recreate the underlying issue.

**Comment by lakerssuperman** [comment]
> I'm unable to recreate the underlying issue.

Oh bother.  And you have .srt based subtitle files?

**Comment by 1hitsong** [comment]
@lakerssuperman Oh oh oh. Got it! I've successfully recreated the issue. Testing forthcoming.

**Comment by 1hitsong** [comment]
This resolves the issue on the movie detail page. 

Will there be separate PRs for tv shows and the video info popup?

image

**Comment by jimdogx** [comment]
> This resolves the issue on the movie detail page.
> 
> Will there be separate PRs for tv shows and the video info popup?
> 

Um yes of course... I totally knew it was an issue on those two places too *cough* *cough*.... 

In all seriousness, in the spirit of small targeted PRs, I'd say yes, let's open a separate issue for those.

**Comment by jimdogx** [comment]
Streaming information popup bug documented here: https://github.com/jellyfin/jellyfin-roku/issues/858

**Review by 1hitsong — APPROVED** [review]

**Comment by lakerssuperman** [comment]
> @lakerssuperman Oh oh oh. Got it! I've successfully recreated the issue. Testing forthcoming.

Woohoo!!

**Pull request merged**
