### PR TITLE
Correctly set focus after exiting a screen created from Extras group

### PR DESCRIPTION
**Pull request by debmint**
**Changes**
Change MovieDetails.brs to not set focus to buttongroup while in Extras group

**Issues**
After commit #fa0e072, any time MovieDetails was re-displayed, focus was hard-coded to set to buttongroup, but after exiting a screen created by extrasGrid, the focus should remain on extrasGrid.  This caused extrasGrid to lock up, with focus set to buttongroup.  The user would have to either hit the back button, or could hit Down Button to get focus back to extrasGrid.

### CODE REVIEW

**Comment by debmint** [comment]
Question:  What I did was to create a boolean variable "defaultFocus" set to true in Init().  Entering Extras sets it to false and sets lastFocus to extrasGrid, exiting Extras sets it back to true.  OnScreenShown() sets focus to buttonGroup if "dF" is true, or value of lastFocus if false.  Would it be better to set defaultFocus to buttonGroup in Init(), extrasGrid on entry into extras, back to buttonGroup on exit, then simply set focus to defaultFocus in OnScreenShown?  The way as is seems to work, but would the alternative be simpler and perhaps more logical?

**Comment by 1hitsong** [comment]
@debmint Submitted a small change to your branch to remove the extra variable. Everything works as expected.

https://github.com/debmint/jellyfin-roku/pull/1

**Comment by debmint** [comment]
> @debmint Submitted a small change to your branch to remove the extra variable. Everything works as expected.

Somehow I submitted to wrong branch - intended it for master  but that's ok, I suppose, as long as it gets submitted.
Thanks for the fix.  It's a much cleaner solution.  As you can see from my second comment, I was not totally happy with my original patch to start with

**Comment by 1hitsong** [comment]
@debmint We no longer merge direct to master. Our working branch is now "unstable" and we'll merge to master only when releasing. If you approve/merge the change I made to your branch, it should automatically update this PR with the update code.

**Comment by debmint** [comment]
On Fri, Jul 29, 2022 at 10:27 AM 1hitsong ***@***.***> wrote:

> @debmint <https://github.com/debmint> We no longer merge direct to
> master. Our working branch is now "unstable" and we'll merge to master only
> when releasing
>
That sounds sensible.   Anyway.. thanks again for the fix.

**Comment by debmint** [comment]
Am I supposed to merge your pull requst into mine?  If so, it seems to want

**Comment by 1hitsong** [comment]
> Am I supposed to merge your pull requst into mine?

Yes. And you're right, I had the PR pointing to the wrong branch. I've updated it to point to fixExtras.

**Comment by 1hitsong** [comment]
@debmint Did you mean for the 2 translation files to be included in this PR too?

**Comment by debmint** [comment]
> @debmint Did you mean for the 2 translation files to be included in this PR too?

No, I didn't.  Don't know how they got there. I submitted this PR from this repo rather than from my fork.  Reckon this had something to do with it?

How to get rid of them?  What would happen if I squash'ed them and did a force push.  Of course that would mess up history for any of you who  have this PR checked out.

If it didn't cause any problem I personally have no problem with leaving them in.  If I need to get rid of them, I may need some guidance on how to do it properly.

**Review by neilsb — APPROVED** [review]
👍

**Pull request merged**
