### PR TITLE
Dont use progress dialog to block inputs

### PR DESCRIPTION
**Pull request by sevenrats**
remove the progress dialog to elliminate the wierd dimming effect that covers the loading spinner.

### CODE REVIEW

**Comment by 1hitsong** [comment]
The approach of making every component (both existing and new) eat the key input doesn't feel right. It's fixing the issue, but not the root cause.

I purpose instead that we use the progress dialog as it's intended to be used and show it as the spinner. Beyond needing to rework the spinner element code, the only issue I see is the ugly rectangle the spinner shows inside of.

It can be removed in the following way.

```
        dialog = createObject("roSGNode", "ProgressDialog")
        dialog.id = "invisibiledialog"
        for each element in dialog.getChildren(-1, 0)
            if lcase(element.subtype()) = "poster"
                element.visible = false
            end if
        end for

        m.top.dialog = dialog
```

**Comment by sevenrats** [comment]
I have not seen an ugly rectangle, but that does segue into my point nicely: the effect of the most recent implementation of the loading spinner appears to vary wildly.  on cewert's machine it appears to work perfectly.  you see an "ugly rectangle"  I see no rectangle but instead see the spinner behind a 20% black tint.  This is my motivation for removing progressdialog, and instead using code which behaves the same on all machines.  Plus, I think we are doing a lot of input blocking that we don't need to do.

**Comment by 1hitsong** [comment]
I meant the ugly rectangle is from the ProgressDialog element. I removed the properties to hide it and when it showed it had the rectangle behind it.

**Comment by sevenrats** [comment]
im testing your changes now. with any luck it will resolve everybody's needs.

**Comment by sevenrats** [comment]
this does not resolve the black tint problem. the Spinner which is supposed to show, which is not a component of the Progressdialog, is still behind some kind of tint caused by the ProgressDialog.

Edit: The issue is that the tint is so dark that sometimes its not even clear that the spinner is there. The 20% I estimated above from memory appears to be too optimistic.

**Comment by sevenrats** [comment]
oh i see what you are saying. you want to use the progressdialog unhidden and use the spinner which is built into the progressdialog?  I will play around with that idea and update this branch if I come up with something

**Pull request closed without merging**
