### PR TITLE
Add a production build workflow

### LINKED ISSUE #1084: Validate version number bump for prod release
**Is your feature request related to a problem? Please describe.**
When it's time for a production release, we merge unstable into master. The app's version number should be bumped at this time. If we forget and no one catches it, we have a release with the same version number as the one before

**Describe the solution you'd like**
Create a new workflow/step to grab the version number from manifest file, package.json, and the makefile and compare it to the latest release's version

### PR DESCRIPTION
**Pull request by cewert**
the zips generated from this new workflow can be uploaded to github and roku for releases. (our current build workflow creates dev builds with dev images)

**Changes**
- Add a new build workflow to build the app for production releases (using `make release` to generate correct images)
  - triggers when pushing to master
- Add new job to `build-prod.yml` to verify that the manifest, package.json, and Makefile version numbers are different than the latest versions in `master`
  - All 3 versions must match
  - Note: The job doesn't verify that the version number increased, only that it's different than the one in master.
- Only run lint workflow for `pull_request`'s
  - No need to run on push since PR was already approved by then

Fixes #1084

### CODE REVIEW

**Review by neilsb — APPROVED** [review]
Looks fine

**Comment by cewert** [comment]
We're going to need someone to edit the repo settings for this PR to go through since it's waiting for a workflow that's never going to run because it's name was changed. We should probably wait till some of the open PRs get merged anyhow because after this is merged every open PR will have the same problem until they pull the new workflow into their PR.

**Comment by cewert** [comment]
I added a job to verify the app version has been changed. You can see it in action here: https://github.com/cewert/jellyfin-roku/pull/1

**Comment by cewert** [comment]
The new job now validates the manifest file, package.json and the Makefile. It compares the version present in the PR branch with the version in the master branch. It also checks that all three new version numbers are the same

**Review by 1hitsong — APPROVED** [review]

**Pull request merged**
