### PR TITLE
Report music playback

### LINKED ISSUE #762: Listenbrainz and Webhook plugins don't work with Roku client, however web interface works fine.
**Describe the bug**
When using Roku app to play music, music plays but related Jellyfin plugins do not work.  Nothing is being reported to Webhook and nothing is being reported to the Listenbrainz scrobbler.  If I play music using the web interface, both plugins work fine.  When using Roku it is as if nothing is happening.

### PR DESCRIPTION
**Pull request by 1hitsong**
**Changes**
Reports play state for music items, similar to video items.

**Issues**
Fixes #762

### CODE REVIEW

**Comment by neilsb** [comment]
Reporting looks good for play and stop and changing tracks, but pausing a track doesn't stop the "current time" in the Dashboard from increasing.

**Comment by 1hitsong** [comment]
In all honestly, I've never used any of the playback tracking before. I had no idea we had real time current position reporting.

Pretty neat.

**Review by neilsb — APPROVED** [review]

**Comment by neilsb** [comment]
Just for future reference, it's easier to re-review PRs if changes are done as new commits, rather than a force push.  Github highlights the files that you've already reviewed that didn't change, and you can compare what has changed.  When merging we generally do a squash merge, so will go into the main code base as a single commit anyhow.

**Comment by 1hitsong** [comment]
Thanks for the reminder. I typically do it that way too. 🤔 I must have let muscle memory take the wheel for a minute.

**Pull request merged**
