### PR TITLE
Check Focused item is valid when Selecting Server

### PR DESCRIPTION
**Pull request by Dimitrije-Ciric**
**Changes**
Added condition to check if itemFocused index is valid before accessing to the content of the focused item.

**Issues**
When a user selects the "*" option on SetServerScreen and the server list is empty app crashes.

### CODE REVIEW

**Comment by Dimitrije-Ciric** [comment]
> **Changes** Replaced `for each` with `for i = 0 to ...` .
> 
> **Issues** assocarray.items() returns an array type object. The problem with `for each` is that when it's used to iterate an array it sometimes randomly skips some element from that array. So it should be only used for iterating associative arrays.

**Review by Dimitrije-Ciric — COMMENTED** [review]
**Changes** Replaced `for each` with `for i = 0 to ...` .

**Issues** `assocarray.items()` returns an array type object. The problem with `for each` is that when it's used to iterate an array it sometimes randomly skips some element from that array. So it should be only used for iterating associative arrays.

**Comment by neilsb** [comment]
> The problem with `for each` is that when it's used to iterate an array it sometimes randomly skips some element from that array. So it should be only used for iterating associative arrays.

Are you sure this is correct?  I've not heard of this before, and the [Roku Documentation for For Each](https://developer.roku.com/en-ca/docs/references/brightscript/language/program-statements.md#for-each-item-in-object) states that it can be used in any object implementing the `ifEnum` interface, which the [roArray object does](https://developer.roku.com/en-ca/docs/references/brightscript/components/roarray.md)

**Comment by Dimitrije-Ciric** [comment]
> > The problem with `for each` is that when it's used to iterate an array it sometimes randomly skips some element from that array. So it should be only used for iterating associative arrays.
> 
> Are you sure this is correct?  I've not heard of this before, and the [Roku Documentation for For Each](https://developer.roku.com/en-ca/docs/references/brightscript/language/program-statements.md#for-each-item-in-object) states that it can be used in any object implementing the `ifEnum` interface, which the [roArray object does](https://developer.roku.com/en-ca/docs/references/brightscript/components/roarray.md)

Yes, I am sure. You can test it, it sometimes randomly skips some elements. I know that they said that, but you can't trust them, roku is like blackbox. Many developers saw that through tests, and I also saw that.

**Comment by neilsb** [comment]
> Yes, I am sure. You can test it, it sometimes randomly skips some elements. I know that they said that, but you can't trust them, roku is like blackbox. Many developers saw that through tests, and I also saw that.

Trying not to de-rail this PR, but have you experienced it in that particular for loop?  If so, is there any steps to reproduce as I've spent some time trying to replicate a problem but have been unable to do so.

I have found other people reporting the issue, so I do not have a problem with the change.  But for future reference could a separate PR be raised changes that are not directly related to the scope of the original PR?  (It can be left in this PR for now - however)

**Comment by Dimitrije-Ciric** [comment]
> 
Sorry for raising 1 PR for 2 separate problems. In the future, I will raise separate PRs. I hadn't tried to test on that loop, I just always avoid using "for each" with an array, because I saw that this error happens.

**Review by neilsb — APPROVED** [review]

**Pull request merged**
