### PR TITLE
Update Artist view to use slider controller

### PR DESCRIPTION
**Pull request by 1hitsong**
**Changes**
Updates Artist view to use slider controller element. This allows us to easily add/remove/control content sections and is the next step in updating our music data and allowing additional sections - such as Appears on and Related Artists.

The expectation is you notice no UI or UX changes. It's all behind the scenes.

### CODE REVIEW

**Comment by 1hitsong** [comment]
Todo: Move overhang off screen when scrolled down.

**Comment by 1hitsong** [comment]
Overhang now hidden when scrolling through sections.

https://user-images.githubusercontent.com/3330318/191137404-45f69b74-21ce-440f-8c37-dbcd5ab6b98d.mp4

**Comment by jimdogx** [comment]
Getting a crash when I click on an album:

Screen Shot 2022-09-24 at 6 42 44 AM

```Invalid value for left-side of expression. (runtime error &he4) in pkg:/source/ShowScenes.brs(393)
Backtrace:
#1  Function createartistview(musicartist As Dynamic) As Dynamic
   file/line: pkg:/source/ShowScenes.brs(394)
#0  Function main(args As Dynamic) As Void
   file/line: pkg:/source/Main.brs(161)
Local Variables:
musicartist      roAssociativeArray refcnt=1 count:15
global           Interface:ifGlobal
m                roAssociativeArray refcnt=3 count:10
musicdata        roAssociativeArray refcnt=1 count:4
group            Invalid
Threads:
ID    Location                                Source Code
 0*   pkg:/source/ShowScenes.brs(393)         group.pageContent = ItemMetaData(musicartist.id)```

**Comment by 1hitsong** [comment]
@jimdogx I can't recreate that. Can you send me a screenshot of the view where you are clicking on the album?

**Comment by 1hitsong** [comment]
Additionally the error code is pointing to a location that creates an ArtistView, not an AlbumView. Yeah, need some debug info here so I can try to create.

**Comment by jimdogx** [comment]
I think I found the culprit: 

```Error creating XML component ArtistView
-- Could not create node of unknown type "bgv_ButtonGroupVert"
-- Error foundpkg:/components/music/ArtistView.xml(29)

**Comment by jimdogx** [comment]
npm install fixed it... I need to setup my dev env to auto do this or something cause I keep forgetting.

**Review by jimdogx — APPROVED** [review]

**Comment by 1hitsong** [comment]
To be merged 9/25 if no issues found.

**Pull request merged**
