### PR TITLE
Add custom subs to QueuePlayer. Fix Next button counter

### PR DESCRIPTION
**Pull request by 1hitsong**
**Changes**
Copies new custom subtitles over to the new global queue video player. Also fixes Next Episode button counter that was broken during custom sub merge.

### CODE REVIEW

**Comment by 1hitsong** [comment]
@jkim2492 This is the PR to pull the custom subtitles into the global queue player. You can test it by playing a video from a playlist. Since I'm copying over your code, do you mind checking it out and ensuring I didn't miss anything?

**Comment by jkim2492** [comment]
@1hitsong Just looked it over and it looks good!

**Comment by 1hitsong** [comment]
Needs updates from #1133 applied to the code

**Comment by 1hitsong** [comment]
Fixed by PR https://github.com/jellyfin/jellyfin-roku/pull/1375

**Pull request closed without merging**
