### PR TITLE
Revert new home screen settings + bugfixes

### LINKED ISSUE #624: Home rows are not being refreshed when the home page reappears on screen
**Describe the bug**
After backing out of a video or exiting the screensaver, the home rows should be "refreshed" but they are not.

**To Reproduce**

1. Start watching a video
2. fast forward to about halfway
3. wait a few seconds so it can update the server of its current playback position
4. hit back
5. observe

**Expected behavior**

Home rows should be updated with the latest data from server

**Logs**

**Screenshots**

**Additional context**

latest version of dev

### LINKED ISSUE #690: TV Show posters not displaying correctly on home screen
**Describe the bug**
Movie posters are "cut off" when displayed on the home screen ("Latest In")

**To Reproduce**

1. Debug latest master
2. Observe home page

**Expected behavior**
Posters display correctly

**Logs**
N/A

**Screenshots**
PXL_20220711_005833876 MP

**Additional context**
This is a properly displayed poster from web client
jellyfin-simpsons-poster

### LINKED ISSUE #692: Latest TV Shows missing number of new episodes
**Describe the bug**
TV show posters on the home screen no longer show the number of new episodes

**To Reproduce**

1. Have TV shows
2. Have Latest In enabled for a TV show library
3. debug latest master
4. observe tv show posters on home screen

**Expected behavior**
Blue circle with the number of new episodes in the top right. Here's a pic from the web client
jellyfin-simpsons-poster

**Logs**
N/A

**Screenshots**

PXL_20220711_005833876 MP

**Additional context**
Introduced in #553 when switching from wide posters to movie style posters
Didn't mark bug since nothing is broken. UX just suffered

### PR DESCRIPTION
**Pull request by cewert**
There were merge conflicts in 3 files. They seemed straightforward but please double check I didn't screw something up
- components/ItemGrid/ItemGrid.xml
- components/data/HomeData.brs
- components/home/LoadItemsTask.brs

**Changes**
Reverts #553

**Issues**
Fixes #624
Fixes #690
Fixes #692

### CODE REVIEW

**Comment by jimdogx** [comment]
Looks like the old home screen except for Collections aren't working.

**Comment by cewert** [comment]
@jimdogx when i select my collections library, I see a list of my libraries instead of collections. Is that what you're seeing too?

**Comment by jimdogx** [comment]
> @jimdogx when i select my collections library, I see a list of my libraries instead of collections. Is that what you're seeing too?

Yes.  If you install 1.4.13 you'll see what Collections should look like 👍

**Comment by cewert** [comment]
Bug was introduced in #596. Collections work as expected the commit before - `git checkout 57c2d502`

Logs say `[LoadItems] Unknown Type: ManualPlaylistsFolder` when selecting a library which points to `LoadItemsTask2.brs` 

~~I'm betting it's the query params that were added: https://github.com/jellyfin/jellyfin-roku/pull/596/files#diff-5f2d03feb1e3a16891ccfd52c24da378e259c33375216a641d6d3b3294bee8d6~~

**Comment by cewert** [comment]
Bug was definitely introduced in #596 but nothing in `LoadItemsTask2.brs` seems to be causing the bug in my testing.

Not sure where to go from here. Going to try banging my head on a wall and see if that helps 😅

**Comment by 1hitsong** [comment]
@cewert In components/itemgrid/itemgrid.brs, on line 119 readd `m.loadItemsTask.itemId = m.top.parentItem.Id` and on line 158, remove setting `m.loadItemsTask.itemId`

This will correct collections. I didn't test any other consequences.

**Comment by candry7731** [comment]
Can we add #553 back into this so I can test and update as that update is more pressing then this one in my opinion.

**Comment by candry7731** [comment]
> Can we add #553 back into this so I can test and update as that update is more pressing then this one in my opinion.

Actually the Playlist PR #638  will fix collections and playlist functionality. As it adds item.type = "CollectionFolder",  item.type = "ManualPlaylistsFolder", item.type = "Playlist" to line 78 in Load ITemsTask2.brs

**Comment by cewert** [comment]
@1hitsong tested collections and they seem to work fine with your fix.

I believe I found a new bug in #596 when viewing options on any library. The tab names and options aren't formatting correctly. This is also what master looks like.
PXL_20220718_220730652 MP
:

**Comment by candry7731** [comment]
> @1hitsong tested collections and they seem to work fine with your fix.
> 
> I believe I found a new bug in #596 when viewing options on any library. The tab names and options aren't formatting correctly. This is also what master looks like. PXL_20220718_220730652 MP :

@neil and I corrected this in Search PR #593

**Comment by cewert** [comment]
I think this is ready to merge @jimdogx @neilsb

**Comment by jimdogx** [comment]
I tested Collections, Options, Home Screen refresh and against my test server (to make sure all rows appear).  Looks good.

**Review by jimdogx — APPROVED** [review]

**Pull request merged**
