### PR TITLE
Cleanup Music Artist screen layout. Use square cover art

### PR DESCRIPTION
**Pull request by 1hitsong**
**Changes**
Cleaned up the Music Artist screen layout to look nicer. 

Updated album row cover art to be a square, which is how cover art is typically shaped. Also updated the music artist grid view to also use square artist images, which again is the typical shape.

### CODE REVIEW

**Review by candry7731 — APPROVED** [review]
Looks great! 

Albums that have images, the bottom corners are squared off and the top corners are rounded compared to the blue default background have all 4 corners rounded.

**Comment by 1hitsong** [comment]
On my Rokus only the top left corner is rounded on everything (movies, music artists, tv shows). You're seeing other corners rounded?

**Comment by jimdogx** [comment]
On a server with Artist / Albums it works great.  On my test server with just Albums, it flickers a lot and there is no backdrop.

**Comment by jimdogx** [comment]
Checking today and I don't have any issues (no flickering).  I've changed my server between from 10.7 and 10.8 several times for testing other things that who knows what state my server is in now LOL.

However, @candry7731 is right, I see rounded corners on the top.  It still looks fine to me, being more square than not, but if your intention was no rounded corners at all, then it might need another look.

**Comment by 1hitsong** [comment]
> However, @candry7731 is right, I see rounded corners on the top. It still looks fine to me, being more square than not, but if your intention was no rounded corners at all, then it might need another look.

The intent of this PR wasn't to remove the rounded corners, although that's a good idea as my Roku doesn't apply them very well anyway, it was to change the shape/dimensions of the photos used for navigation in a Music library since most artist and album images are square.

**Comment by jimdogx** [comment]
> The intent of this PR wasn't to remove the rounded corners, although that's a good idea as my Roku doesn't apply them very well anyway, it was to change the shape/dimensions of the photos used for navigation in a Music library since most artist and album images are square.

In that case, it's working as intended 👍

**Review by jimdogx — APPROVED** [review]

**Pull request merged**
