### PR TITLE
Move selected subtitle to top of selection menu

### PR DESCRIPTION
**Pull request by 1hitsong**
## Changes
Puts the currently selected subtitle track at the top of the subtitle dialog selection options.

We're unable to set cursor focus to the item when we show the dialog, though the track's radio button is preselected. For videos with a lot of subtitles, this can cause the selected track to not show without scrolling down to find it.

This ensures the selected subtitle track is seen by the user without requiring them to first scroll.

### CODE REVIEW

**Comment by cewert** [comment]
What do you think about `None` always being at the top with the selected subtitle always 2nd right under it so we know it's visible to the user? The consistency of `None` being at the top would be better IMO.

**Comment by 1hitsong** [comment]
I wouldn't mind that, if we could make the cursor start from the currently selected item, which I can't.

No matter what, the cursor will always be on the 1st item in the list. IMO it makes sense for the cursor to start on the selected item, then the user's input changes it.

With None being first, the cursor starts on None, but the selected subtitle will be in position 2. It really messes with the UX.

**Comment by cewert** [comment]
> With None being first, the cursor starts on None, but the selected subtitle will be in position 2. It really messes with the UX.

I don't understand how that messes with UX. Why does the currently selected item need to be at the top when we have the radio button to tell the user which option is selected? 

The most common use case in my mind for opening the CC dialog when subs are already turned on, would be to turn them back off. So we always keep the CC options in the same order which makes the dialog more intuitive (None is always at top regardless if you have 0 subtitles, subs turned on etc.) and also keeps one of the most common user actions for that dialog at the top and easiest to get to (turning subs off).

**Comment by 1hitsong** [comment]
This video shows an example of why I want to move the active subtitle to the top. The user must scroll down to see what's active 🤮. With this PR, the active subtitle will be at the top of the list, and when shown, the user's cursor will be focused on the selected subtitle. There can be no confusion, to change the subtitle they must press down and select something else.

If the active subtitle were 2nd, then the user's cursor would be focused on a new, different option. The UX in that case would allow them to change the selected subtitle having never pressed up/down to actively select a different subtitle.

https://github.com/jellyfin/jellyfin-roku/assets/3330318/3531118a-84aa-4ffd-be94-a335c067e3a5

**Comment by cewert** [comment]
> This video shows an example of why I want to move the active subtitle to the top. The user must scroll down to see what's active 🤮

I agree that the currently selected subtitles should somehow be visible to the user when the dialog is opened.

> If the active subtitle were 2nd, then the user's cursor would be focused on a new, different option. The UX in that case would allow them to change the selected subtitle having never pressed up/down to actively select a different subtitle.

Correct, my suggestion means it would always be focused on "None". Users would be able to toggle subs off without hitting up/down but not actually change subtitles. If the user wanted to change subs they would still have to scroll past the first two entries in the list regardless whether "None" or the active subs are first in the list.

**Review by neilsb — APPROVED** [review]

**Pull request merged**
