### PR TITLE
Add song track number and length to album view

### PR DESCRIPTION
**Pull request by 1hitsong**
**Changes**
Add additional song information to the song list on the music album page. Add track number (if available) and the track length.

If track number is not available, we display nothing, just like web view.

WIN_20220716_19_47_44_Pro

WIN_20220716_19_48_47_Pro

### CODE REVIEW

**Comment by jimdogx** [comment]
This is a great addition.  Only comment, when I am connecting to a remote server, it takes a good 3 - 4 seconds for the tracks to show up.... so you're staring at a blank list with "play now" and "instant mix".  Would it be better to show "Loading..." at the top (like TV episodes do while they're loading) and have the buttons disabled until everything is loaded?

**Comment by 1hitsong** [comment]
@jimdogx Does master act the same way?

**Comment by jimdogx** [comment]
> @jimdogx Does master act the same way?

Just checked.  Yes it does.  I could have sworn the buttons were disabled at one point until everything loaded.

**Comment by 1hitsong** [comment]
> I could have sworn the buttons were disabled at one point until everything loaded.

You and me both. 🤔 

I added a loading spinner to the song list. Check it out. I did it blind since I don't see/experience the issue locally.

If this doesn't fix it, I'll need to reach out to someone in chat to get remote access somewhere.

**Review by jimdogx — APPROVED** [review]

**Comment by lakerssuperman** [comment]
> 

Looks great!!

**Pull request merged**
