### PR TITLE
add optional blurhash to new layouts

### PR DESCRIPTION
**Pull request by sevenrats**
Just ports the old pr to the new views.

### CODE REVIEW

**Comment by sevenrats** [comment]
this now contains a bunch of changes that are more rightly in #976, because it depends on them.  once that is merged i will pull them from here and mark as ready and squash

**Comment by candry7731** [comment]
Getting compile errors

image

**Comment by sevenrats** [comment]
> Getting compile errors
> 
> image

i think the issue you are experiencing is perhaps that you did not rerun npm -i to install fake blurhash 1.0.3-beta. it appears the compile error is in moviedata, which, I dunno.  This branch has conflicts right now, so, that probably makes sense.

**Comment by candry7731** [comment]
Where we at with this? Do you need help merging the conflicts?

**Comment by sevenrats** [comment]
yeah ill take any help you have to offer.  This was on hold because 1hitsong was changing the ui at the speed of light, so it was pointless to try and keep up.  now that that has cooled down it may be reasonable to try again.
the main holdup, and the cause for the lack of support, is that in the vast majority of environments, its hard to get these to show up because they take approximately 15 miliseconds each to render on modern roku (who knows how long on an old one).  this results in a bit of a slowdown, and you never see them.  on low powered hardware such as with a pi server, they make a huge positive impact, and the loading time is negligible.  So, we can't just load them all in the brutal way that this PR does.  some consideration has to go into the speed of the connection, the current library view (we can load as few as 30 in presentation but have to load like 100 in grid), etc etc.  Would very much welcome any input on this.
Maybe it would be enough to just make a setting for it, but really it would be nice to make the implementation appropriate for all applications instead of just a gimme for low-powered ones.

**Comment by sevenrats** [comment]
also im pretty sure this is using fake-blurhash the ropm package, which, there is no reason we can't just pull it into the repo as long as I get a one-line at the top of the file.  neil should have one too since its made out of code I stole out of his trashcan.

**Comment by cewert** [comment]
@sevenrats Are you still working on this? It's been 8 months with no updates

**Comment by sevenrats** [comment]
still going to write this but it will be nothing like this draft.

**Pull request closed without merging**
