### PR TITLE
Setup rooibos test framework

### PR DESCRIPTION
**Pull request by cewert**
This PR removes the current Roku testing framework and replaces it with the the [rooibos testing framework](https://github.com/georgejecook/rooibos). The goal of this PR is to have a stable base for us to build future unit tests on.

~~There are currently only 3 tests and they are only examples from the [rooibos sample repo](https://github.com/georgejecook/rooibos-roku-sample).~~ To build the included tests from the CLI, type `npm run tests` (there is currently no way of running the tests from Makefile). To run the included sample tests from VSCode, go to the `Run and Debug` tab, from the dropdown in the top left select `Run tests`, and then hit F5 or click the green "Play" button. This will run ALL of the tests found inside of the "test-app" folder on your local Roku device.

What's with the other option listed in the `Run and Debug` dropdown named `Run test-tdd`?
This is meant for devs who are writing tests. It allows them to run only the tests they are working on and ignore all the rest. To use it, create a file called `bsconfig-tdd.json` in the root folder of our project - a sample is provided [here](https://github.com/georgejecook/rooibos-roku-sample/blob/master/bsconfig-tdd.json). If you look at the `files` array in the sample file you'll notice that ALL testing files are being excluded except for the 4 files listed at the bottom. So whichever new files you are working on get added to this list and are the only ones tested. Because the list of files will constantly change, this file has been added to the `.gitignore` file to prevent anyone from accidentally committing it to git.

## Changes
- Remove official roku testing framework
- Setup rooibos testing framework
- Updated NPM dependencies where needed
- Lock all NPM dependencies to a specific version
- Sort NPM dependencies alphabetically
- Moves all functions out of `Main.brs` so they can be unit tested

### CODE REVIEW

**Comment by cewert** [comment]
~~According to the docs, rooibos will [only work with brighterscript v0.52.3](https://github.com/georgejecook/rooibos/blob/master/docs/index.md#your-project-must-use-vscode-and-the-brighterscript-compiler) but~~ rooibos worked just fine during my testing using the latest version of brighterscript - v0.62.0

the repo owner confirmed on slack that rooibos works with the latest version of brightscript 👍

**Comment by cewert** [comment]
I'd like to have a couple working tests instead of samples. Marking as draft till it's ready

**Comment by cewert** [comment]
Instead of the example, I now have two functions we actually use being tested:
- `isValid()`
- `isValidAndNotEmpty()`

I also made the folder structure for the testing files mimic the folder structure of the source files.

**Comment by 1hitsong** [comment]
On first run I got the error `cannot find .env file`

I created a blank file in place, and tried again. The build failed with a new error `'rm' is not recognized as an internal or external command,`
image

I'm running Windows 11, which is likely important.

**Comment by cewert** [comment]
@1hitsong Sorry, good catches. Both of your issues should now be fixed.

**Comment by cewert** [comment]
Going to stop fixing merge conflicts due to dependency updates until this is reviewed/approved.

**Comment by 1hitsong** [comment]
Success!

image

**Comment by 1hitsong** [comment]
To add to the Changes bullet list, this also moves some functions out of main.brs and into source\ShowScenes.brs

**Review by 1hitsong — APPROVED** [review]

**Comment by cewert** [comment]
> To add to the Changes bullet list, this also moves some functions out of main.brs and into source\ShowScenes.brs

Thanks for bringing that up. The reason for doing that is because nothing in `Main.brs` can be unit tested. So I moved all functions to a different file. Don't remember my reasoning for using `ShowScenes.brs` so I'm open to suggestions.

**Comment by 1hitsong** [comment]
I think it's fine. ShowScenes seems as good a place as any other.

**Pull request merged**
