### PR TITLE
Retain view/sort/filter settings for collections

### LINKED ISSUE #444: Remember Live TV View Selecton
**Is your feature request related to a problem? Please describe.**

I prefer the guide view over the channel list but I have to manually switch to it every time I open the app because it defaults to the channel view.

**Describe the solution you'd like**

I would like the Roku app to remember my selection when I change the Live TV Channel View and automatically apply it every time I go to the Live TV portion of the app.

**Describe alternatives you've considered**

An alternative would be to simply change the default to guide view but then anyone who prefers the channel sort view would have the same issue.

**Additional context**

Applies to the Roku app both Stable and Beta.

### PR DESCRIPTION
**Pull request by jdlayman**
**Changes**
Updated collections so that any options for view/sort/filter that are selected are retained after leaving the scene.

**Issues**
Fixes #444 

**Discussion**
@neilsb, I saw your discussion on #444 about whether these selections should sync to server and be retained between clients. If we decide we want that, I could work on getting that added. This was driving me nuts on LiveTV though, where I really like to have my guide filtered to favorites.

I know you mentioned you were doing work in this area, so if this isn't aligned with larger vision, no worries. I just figured I would share it in case its helpful. I'm using the code locally and it works well. I left it as a separate PR from the other bug fixes to make the others easier to merge in case you had reservations on this one.

### CODE REVIEW

**Comment by neilsb** [comment]
This all seems to work as described, which is great.  I don't have a a problem with this at all, I think the comments in #444 were more related to whether a user would want **all** their Roku settings synced to all their Roku devices when using a server, and to be honest the only times I can come up with this wouldn't be the case are maybe a bit contrived.  But if (when the settings screen exists) one of the settings is a "Sync settings with server" then I think that would cover the issue anyhow.

With this change, do you think we need to add something to the ItemGrid screen to display the current filter/sort settings?

**Comment by jdlayman** [comment]
Yes. I definitely think it would be good to indicate if a view is filtered. I'm a little less worried about sort, but if we come up with a good space for it, it would be easy enough to add. Do you have any thoughts on where it might make sense to put it? Best idea I have so far is to add some the filter in parenthesis in the title section, e.g. "Live TV (Favorites)". Would only include if filter is not equal to "All".

Also, I noticed the program details section was hiding the `* Options` field for Live TV. I just pushed a fix for that to this PR as well. I had to shrink the details poster just a bit, so let me know what you think of that.

**Comment by neilsb** [comment]
> I'm a little less worried about sort

Yeah, forget sort actually.  :)

> Best idea I have so far is to add some the filter in parenthesis in the title section, e.g. "Live TV (Favourites)". Would only include if filter is not equal to "All".

Yup, that sounds good.  Possibly using a smaller font?  (Although that may be trickier with it being a scrolling label).  Another possibility could be directly underneath the title but still in the header.  
image

Given that in the future, multiple filters would be able to be applied I think it probably makes sense to just show "Favourites" or "Filtered" or nothing - rather than trying to display the full filter information in the header.  Not that this relevant right now, just thinking ahead

 
> Also, I noticed the program details section was hiding the `* Options` field for Live TV. I just pushed a fix for that to this PR as well. I had to shrink the details poster just a bit, so let me know what you think of that.

Yup - looks good.

**Comment by jdlayman** [comment]
I tried adding a label to the right of the title, but as you suspected it was challenging because we reserve the full space for super long titles. I'll experiment with either appending to the existing title or sticking it below. If I stick below, I think I'd want it to only shift the title up if there was something to render.

To be able to update overhang details dynamically, we'll need to set up some kind of observer so the group can change its own title/filter/etc. Was trying to think of an elegant way to do that, but not coming up with much better than observing `group.overhangTitle` within main.brs. The group shouldn't change the overhang itself because it doesn't know if it's active and the overhang can't observe the group, because it can't easily unobserve if it changes. We'll see if more sleep provides a better solution :).

I got distracted by a couple rabbit trails (prototyped getting the actual show posters instead of channel posters for the program details). Tomorrow night is date night, so it may be a few days before I wrap this up.

Thanks for the thoughts!

**Pull request closed without merging**
