### PR TITLE
Set Maximum Bitrates values based on Roku Guidelines

### LINKED ISSUE #401: H265 HDR video not playing
**Describe the bug**
When trying to play a 4K H265 HDR video the first couple of seconds play and then the loading bar appears indefinitely and the server's admin dashboard no longer says the video is playing.
I have tested this on both the stable and beta releases and get the same behaviour.

**Expected behaviour**
The video to direct play and audio to transcode fine (since AC3 is not supported on the Roku).

**Logs**
FFmpeg Direct Stream log from Jellyfin server
```
Stream #0:0(eng): Video: hevc (Main 10), yuv420p10le(tv, bt2020nc/bt2020/smpte2084), 3840x2160 [SAR 1:1 DAR 16:9], 23.98 fps, 23.98 tbr, 1k tbn, 23.98 tbc
    Metadata:
      BPS-eng         : 73199888
...
    Stream #0:2(eng): Audio: ac3, 48000 Hz, 5.1(side), fltp, 448 kb/s
    Metadata:
      title           : Surround 5.1
      BPS-eng         : 448000
...
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:2 -> #0:1 (ac3 (native) -> aac (native))
```

**Additional context**
The server is being run on a Raspberry Pi 3 running Jellyfin 10.7.1.
Video transcoding is disabled for the user account being used.
Audio transcoding is enabled for the user account being used.
The video plays fine on Windows with the Desktop application.
Roku streaming stick plus being used.

### LINKED ISSUE #722: Suddenly incorrectly transcoding 4k x265 HEVC files on one TV
**Describe The Bug**

4k x265 files stopped trasncoding correctly for a TV that only understands h264 at a maximum of 1080p, only showing a black screenw ith no sound. It's a Roku TV, so no options during playback. 720p and 1080p files encoded with h265 play back fine, so it seems to be that they're not being downscaled anymore. The actual resolution being delivered does not show in transcoding info.

**Media Information**

Entire log directory missing in Windows build or location not documented for Windows. Logging.json does not contain a save directory. Ffmpeg not installed as far as I know.

**Screenshots**

image

**System (please complete the following information):**
 - Platform: Roku
 - Jellyfin Version: 10.8.1

### PR DESCRIPTION
**Pull request by ApexArray**
**Changes**
Set max bitrate for each codec profile according to Roku [Supported video codecs
](https://developer.roku.com/en-gb/docs/specs/media/streaming-specifications.md#supported-video-codecs)

**Issues**
Fixes #722
Possibly fixes #401, #449, #496
Likely fixes the issues observed in #541. We could also set these limits from a user setting if desired.

### CODE REVIEW

**Review by jimdogx — APPROVED** [review]

**Comment by NeuroDawg** [comment]
Please don't start setting maximum bitrates based upon that Roku chart. As I mentioned in #944, this chart isn't accurate. I have no problems direct streaming (audio has to be transcoded) blu-ray remuxes from makemkv that are >20Mbps in h264 codec, using Jellyfin client on a Roku 4. I'd hate to see my files transcoded to a lower bitrate just because Jellyin thinks it can't play them.

**Comment by thegreatprophetzarquon** [comment]
Yes, these limits don't seem accurate at all. I think that has to be for older models, perhaps for the the express stick, or just potentially very conservative. On my 2019 Roku Ultra, I've had Plex stream AVC bluray remuxes with no transcoding at around 40mbps with no issue and played at least one HVEC 4K UHD remux just fine (definitely over 40mbps). I'm very sure many official apps use higher bitrates than 10mbps for h264.

I just set up a Jellyfin sever and the 10mbps bitrate limit that's hardcoded right now is a deal breaker for using the Roku app. This looks terrible for many films: certainly anything with film grain. 
The option to set/remove this limit (either in the client or from the server side) is most desirable, (#541) but absent that you should remove or raise this, at least for the moment.

**Comment by thegreatprophetzarquon** [comment]
And I see #975 is giving the option to disable this, fantastic. (although I really don't think 10Mbps is a good default limit for AVC; that's not a real device limitation and should be set higher). All good, don't mind me. lol.

**Comment by ApexArray** [comment]
Wow, so sorry for the issues that this has caused.

I was indeed developing and testing on an older Roku 4200X, and the bitrate limitation was the only thing that fixed my issue. Making this a user setting is definitely the right call.

**Pull request merged**
