### PR TITLE
Fix Audio Track Selection

### LINKED ISSUE #500: Audio track selection doesn't play proper track
**Describe the bug**
Movies with multiple audio tracks play default track despite selecting alternate audio track

**To Reproduce**

1. Select movie with multiple audio tracks
2. Move highlight to "Audio" selector
3. Select alternate track from list
4. Press "back" button to get back to main item page
5. Select "Play"
6. Audio will be whatever is default, not what was chosen

**Expected behavior**
Audio track played should be what was selected

**Additional context**
I have several movies with three audio tracks.  A 5.1 track, a stereo track, and a stereo track with "Rifftrax" mixed in.  When I select the third track to have the Rifftrax jokes, I get the default 5.1 track.

I'm not sure if this is a result of the new 10.5 RokuOS update.

### PR DESCRIPTION
**Pull request by neilsb**
`MediaSourceId` is required when selecting an audio track during transcoding, and PR #504 resulted in this being an empty string.  

**Changes**
 - Revert commit for PR #504

**Issues**
 - Fixes #500

### CODE REVIEW

**Comment by neilsb** [comment]
A quick test appears to show that reverting #504 does not cause the issues reported in #467 & #397 to reoccur.  May need to revisit these 2 issues if the problems are reported again.

**Comment by jimdogx** [comment]
> A quick test appears to show that reverting #504 does not cause the issues reported in #467 & #397 to reoccur. May need to revisit these 2 issues if the problems are reported again.

Looking back, I wonder if this was actually a server issue?  The issue was that the **server** was replying with "NoCompatibleStream".  And at the time I was connecting to an alpha (not even a beta) version of the Jellyfin server.  Not knowing enough about Jellyfin at the time, I didn't even think to look server side.

**Comment by neilsb** [comment]
> Looking back, I wonder if this was actually a server issue?

For #467 that may well be the case, and not overly bothered about.  It's not a goal of the app to be compatible with Emby, and as the servers diverge further the client is definitely not going to continue working with Emby.

For #397 is may be a server issue.  I don't have a Roku TV to test with, so if we get any further reports of it some more investigation can be done - but as long as the revert doesn't consistently break playback on Roku TVs then I don't think it's a big worry right now.

**Review by anthonylavado — APPROVED** [review]

**Comment by anthonylavado** [comment]
Will make emergency release for this.

**Pull request merged**
