### PR TITLE
Auto Reload LiveTv when feed Errors

### PR DESCRIPTION
**Pull request by candry7731**
This added the ability for the LiveTv to auto reload when the feed "Finishes" unexpectedly.

Currently, when a feed errors you are kicked to the guide and then have to move up or down the guide then go back and select the channel again to get it to reload.

**Issues**
Show the guide for a second or two... not a huge issue but the user might not realize it's going to auto reload. Might have to rethink and maybe display a reload screen or spinner

### CODE REVIEW

**Comment by 1hitsong** [comment]
It looks like in its current state, this would remove a lot of code needed for music support.

**Comment by candry7731** [comment]
That's why we need to get a release out! To many pr's have been submitted
and when trying to build on top things get messy

**Comment by neilsb** [comment]
If you can ensure that all branches are created on master, then that should stop this sort of problem happening.

LiveTV is not working on my Roku at all at the moment, so I'll need to look into that.   What's the best way to test this (i.e. cause the stream to end prematurely)?

**Comment by candry7731** [comment]
> If you can ensure that all branches are created on master, then that should stop this sort of problem happening.
> 
> LiveTV is not working on my Roku at all at the moment, so I'll need to look into that. What's the best way to test this (i.e. cause the stream to end prematurely)?

I will send you a private message on matrix with a m3u link to test. This feed should drop every few minutes and reload automatically. I would love to not be able to pop the scene then add it back... but this is better than nothing.

**Comment by 1hitsong** [comment]
@candry7731 
These 4 lines appear to be working as expected; however, there is a lot of code this PR would remove that we need to keep.

if selectedItem.Type = "TvChannel" and node.state = "finished"
sceneManager.callFunc("popScene")
video = CreateVideoPlayerGroup(node.id)
sceneManager.callFunc("pushScene", video)

**Review by 1hitsong — CHANGES_REQUESTED** [review]
Added code works as expected, but this PR would remove a lot of other code we need!

**Comment by candry7731** [comment]
We should be good on this now? Since I merged the unstable branch?

**Comment by 1hitsong** [comment]
@candry7731 Not quite. Main.brs would still get mangled. Check out all the code that would get removed on merge: https://github.com/jellyfin/jellyfin-roku/pull/669/files

**Comment by candry7731** [comment]
> @candry7731 Not quite. Main.brs would still get mangled. Check out all the code that would get removed on merge: https://github.com/jellyfin/jellyfin-roku/pull/669/files

Can you check this? I added all of the removed code back into the main.brs file

**Comment by neilsb** [comment]
Reverted the last couple of files to leave just the changes for this PR.  I can't confirm it's working as with HDHR this makes no difference when I'm testing.   @candry7731 you were going to send me a m3u link to test with, but not sure you ever did.

**Review by alanazar — APPROVED** [review]
Replicated the issue on the unstable branch
Tested this PR and it works as intended. Reloads the feed if it cuts instead of taking the user back to the TV Guide screen

**Review by 1hitsong — APPROVED** [review]

**Review by neilsb — APPROVED** [review]

**Comment by dahartigan** [comment]
Thank you for forcing it to reload after a failed stream.  I have had it succesfully restart a stream, except there was an instance where the Roku app gave an error "Error during playback - An error occured while playing this item." with an OK button.  It's crashed here, however in the console (vscode) is shows the following error:

```
=================================================================

Warning occurred while setting a field of an RoSGNode
-- Tried to set nonexistent field "lastfocus" of a "JFVideo" node
   at line 21 of file pkg:/components/data/SceneManager.brs
=================================================================
```

I hope this helps :)

**Pull request merged**
