### PR TITLE
Enabled all titles to show under poster images

### LINKED ISSUE #365: Add option to display video titles always instead of when highlighted
**Is your feature request related to a problem? Please describe.**
On the video list, it shows the box art for each video.  If you move your cursor to highlight a video, after 0.5 seconds, it displays that video's title in plaintext beneath the art.  Hiding the title like this makes it slower to find what we're looking for if we want to find a video by reading the plaintext titles rather than trying to parse the artistic title out of the box art with our eyes.

**Describe the solution you'd like**
Add a setting that lets us "Always show video titles".  Then, the video titles should always appear beneath every video, not just the one we have highlighted.

Add another setting called "Disable title fade-in" that makes the title appear instantly when you highlight a video rather than the 0.5 fancy delay behavior that shows the title only after the box art zooms in.  Some people may prefer this rather than using the first setting that shows all titles constantly.

**Additional context**
Plex for Roku does this by default.

### PR DESCRIPTION
**Pull request by candry7731**
#365  - Enable Titles to show when grid is loaded instead of on focus... 

**Changes**
Set scrolling label to visible

### CODE REVIEW

**Comment by neilsb** [comment]
This looks good, but I'd like to hold off this until we get the client side setting place, so a user can choose to switch whether to have them on or off in the preferences.

I'll make a concerted effort to get that in place this week (sorry for the delay), and it'll be a trivial change to check that in this PR.

**Comment by neilsb** [comment]
I've hooked up a user setting for this, now the settings screen is in place.

I've had a play with your changes, and have a couple of things for discussion regarding long titles

 - Item titles are currently Scrolling Labels.   When they're are always displayed, do we want them always scrolling, or should they only scroll when the item is highlighted?
 - When you've got a couple of items with long titles together, the titles now run into each other (especially if scrolling).  I think it may be good to do something to address this.
 
image

**Comment by candry7731** [comment]
> I've hooked up a user setting for this, now the settings screen is in place.
> 
> I've had a play with your changes, and have a couple of things for discussion regarding long titles
> 
> * Item titles are currently Scrolling Labels.   When they're are always displayed, do we want them always scrolling, or should they only scroll when the item is highlighted?  **_I set this to only scroll when item has focus. I think this works better_**
> * When you've got a couple of items with long titles together, the titles now run into each other (especially if scrolling).  I think it may be good to do something to address this. **_I updated the text width to be smaller and this this gives more padding left and right_**
> 
> image

**Review by neilsb — APPROVED** [review]

**Comment by candry7731** [comment]
Sounds good! Just trying to implement some of the feature requests.

**Pull request merged**
