### PR TITLE
Librarylist images

### PR DESCRIPTION
**Pull request by cewert**
This adds images for each library on the home screen and resizes the rowlist to accommodate them.

I also added an image for "Live TV" library since an image is never created for it on the server and it looked bad in the rowlist without one. I noticed the web client uses material icons so I used the [same one](https://material.io/resources/icons/?icon=live_tv&style=baseline). I assume since we are using it on the web client that licensing won't be an issue? but I'm not positive and would like someone to confirm before we merge this.

Also, even though the default value for `overhang.height` is 115, using RALE I noticed my `overhang.height` was being set to 172. I searched the code to see if we were changing it but found nothing so I manually set it to 115 if the `themeScene()` function and adjusted the logo to match.

**Issues**
Partially addresses #16

### CODE REVIEW

**Comment by cewert** [comment]
I just realized I didn't test this with any music libraries. I have no idea if images exist for those. I'll make a test library tomorrow to test.

**Comment by dkanada** [comment]
> I assume since we are using it on the web client that licensing won't be an issue?

All Material Design icons are free to use under a permissive license if I recall, but you don't necessarily need to use them if Kodi generally has a different icon style.

**Comment by cewert** [comment]
My tests showed the server never made an image for music libraries so I added an icon for it.

**Review by bisby — APPROVED** [review]
The current buttons are framed around the idea of the `My Media <small>` selection (which is what I use on web).  But this looks nice and would make more sense for a TV ui.

**Pull request merged**
