### PR TITLE
Don't pre-populate password field

### PR DESCRIPTION
**Pull request by neilsb**
As reported by _igbo_ on matrix, the password field was pre-populated when logging in, meaning that a user could not securely "sign out" as when they username/password box were shown again they were pre-populated with last login details.

This was a result of #355, to prevent having to re-enter details where there was a transient server availability error.

**Changes**
 - When user selects **Sign Out** from the menu, remove cached username and password

### CODE REVIEW

**Comment by neilsb** [comment]
We should not be storing the password on the Roku, just the user token.  When the login functionality is re-written this can be addressed, and be more tolerant of server unavailability issues to ensure we don't un-do functionality of #355

**Comment by dkanada** [comment]
I would suggest two logout methods, one of which only switches the active user without removing their credentials. I implemented something similar in Gelli and it brings Jellyfin closer to a Netflix style authentication system, which I'm sure lots of people would appreciate.

**Comment by neilsb** [comment]
When you say "Without removing credentials" do you mean so the user still exists on the list?  Even with Netflix if you switch from A to B, then back to A you still need to re enter the pin for A. 

That's the way I'm looking at implementing when reworking the login screen/process.

**Comment by dkanada** [comment]
Ah, that's only when a pin exists :p my family has never even bothered with pins haha.

**Review by anthonylavado — APPROVED** [review]

**Pull request merged**
