### PR TITLE
Allow user to change subtitle track during playback

### PR DESCRIPTION
**Pull request by thomabx**
Allows user to change subtitle track during playback. Creates dialog asking user to select the subtitle track and changes playback if a different track is selected.

Currently it is mapped to down press during playback. No UI element has been added at this time but it can be mapped if one is made.

Its appears default behavior on text subtitle tracks is to only load from the bookmark when playback is started. If you rewind before the bookmark position, changing a text subtitle would cause the playback to jump to the bookmark. Initiating new playback with the 

With video that requires transcoding, it didn't change the stream in my testing with text only subtitles. If video subtitles are being used, any changes require the stream to be transcoded.

**Changes**
All text subtitles tracks loaded into video regardless of use.
Text subtitles are suppressed unless selected track is a text subtitle.

### CODE REVIEW

**Review by cewert — CHANGES_REQUESTED** [review]
Overall this looks great and worked well for me.

There was one thing i noticed that I think we should get fixed before we merge.

When pressing down to make the subtitle menu appear, it not only shows the subtitle dialog but also moves the selection down one.

**Comment by thomabx** [comment]
Right now, it is set to focus on the currently selected track. Default behavior right now is to play a subtitle in the preferred language and if none are in the preferred language it will play the first track. It defers to the Roku's closed captioning settings for actual display.

The first option of None overrides the Roku settings and will turn off subtitles even if the Roku is set to display them.

Is it always moving down one or just initially?

Edits: sorry, on phone.

**Comment by cewert** [comment]
I only have a few files with subtitles and the ones I have show up as "Undefined" for some reason so I wasn't able to test default behavior (I don't ever use subtitles).

> Is it always moving down one or just initially?

It's always doing it for me. Press "down", dialog appears with the top "None" option selected, then almost immediately the selection moves down by one. Exit dialog, hit "down", then the same thing.

**Comment by cewert** [comment]
@thomabx tested some more and it seems that the file was playing "Undefined" by default. If I select "None" then open the dialog again "None" stays selected.

**Comment by thomabx** [comment]
I can change the focus before showing the dialog. 

Some of my media has an Undefined language too. It comes from the server with the language as undefined and the web client lists the same.Does the web client list the language for those files?

**Comment by cewert** [comment]
> I can change the focus before showing the dialog.

Yea that would help a lot

> Does the web client list the language for those files?

Yea web client also shows "Undefined"

Perhaps we should only set default subtitles when `language <> Undefined`?

**Comment by thomabx** [comment]
All of my files with "Undefined" language are still English subtitles. But I've only found two that way.

Right now, it gets the preferred subtitle language from the Roku but ultimately we should get it from the server. I could go either way on whether to display undefined tracks by default.

**Review by cewert — APPROVED** [review]

**Comment by cewert** [comment]
> it gets the preferred subtitle language from the Roku but ultimately we should get it from the server

Agreed. We should probably make an issue for that so it doesn't get forgotten
> I could go either way on whether to display undefined tracks by default

Same. Since we're already loading subs by default I say we leave it as is for now.

**Comment by anthonylavado** [comment]
I know this is merged and all, but for reference, the episode excerpts of Pioneer One on the public demo server have multiple  subtitle tracks, in different languages, and all with the correct language labels (I made sure it was tagged). You can use that for testing :-)

**Pull request merged**
