### PR TITLE
Merge video and audio options

### PR DESCRIPTION
**Pull request by debmint**
**Changes**

Merge media sources and audio channels under one button - Labeled "Options" - on the Movies Details page.  The original commit had separate buttons for each and called up separate menus.  This commit was built upon that and combined the buttons and merged the menus.  There is also an indicator - sort of a superscript - beside the Audio and Video displays indicating when there are additional choices available

**Issues**

There are no real problems that this fixes, just gives an alternate approach to dealing with the choices.

### CODE REVIEW

**Comment by debmint** [comment]
This is an attempt to follow a suggestion by @neilsb as I understand him.  I'm putting this up for review to see if this would be a good alternative

**Comment by neilsb** [comment]
I like how that works.  Makes sense to me, but would be good to hear what other people think.

Aesthetically, could maybe do with a little space between the end of codec and the new label, and not sure the bold font is needed.

**Comment by debmint** [comment]
> I like how that works. Makes sense to me, but would be good to hear what other people think.

Yes, it would be good to get some input due to the many choices.  I sort of like the idea presented in my other PR, but this seems to be a good option.

> Aesthetically, could maybe do with a little space between the end of codec and the new label, and not sure the bold font is needed.

No problem adding space, but do you really think it's needed?  Often a superscript is sort of crowded near what it's annotating?  Re: the bold font.  on my set, at least, it seemed a bit faint without it.  Did you try removing the bold spec to compare?  I would have liked to have the superscript text a bit smaller, but from my experimenting, you cannot change the size of system fonts - is that correct?

I'll play around with it some more following your suggestions and see what I can come up with.

**Comment by neilsb** [comment]
Probably right about the space. Fine just to leave it. 

You can set the font size in the for the system fonts I'm pretty sure. From memory you can just set the size property in brs file (maybe in xml too)

I'll check out the other PR tomorrow and give it a proper try. 😄

**Comment by debmint** [comment]
> Probably right about the space. Fine just to leave it.

I'll experiment with adding space

> You can set the font size in the for the system fonts I'm pretty sure. From memory you can just set the size property in brs file (maybe in xml too)

I thought I tried setting size and it didn't seem to affect it, but will re-check.  Do you think it would look better if it were a bit smaller?

> I'll check out the other PR tomorrow and give it a proper try. smile

I set it to not display if only only one media source.  This could be done with audio as well.  That way, the buttons would not be there to be a distraction, so to speak.  I may have discovered how to handle the buttons, with ButtonGroup, now.  Haven't tried, but I think you could add the buttons by string, the  call getChildren() and cycle through them and set id baed on the text.  I was not using getChildren() correctly when I tried it before

**Review by neilsb — APPROVED** [review]
Looks good 👍

**Comment by jimdogx** [comment]
Late to the party, but wanted to say @debmint that I love the combined video/audio in to one "Options".  Way cleaner than what I did 👍

**Comment by debmint** [comment]
> Late to the party, but wanted to say @debmint that I love the combined video/audio in to one "Options". Way cleaner than what I did +1

Thanks for the comment.  I had thought jellyfin-roku needed this ability to play all available versions, but I don't know if I'd have been able to implement it without your providing the initial starting point.  I just built upon what you had done.

**Pull request merged**
