### PR TITLE
Add function to load default subtitles according to user settings on the global player

### LINKED ISSUE #850: Forced Subtitles Are Not Automatically Displayed During Playback
Issue: Forced subtitles are not automatically displayed when starting playback of a movie and must be manually enabled.
Server version: 10.8.7
Client: 1.6.1 / whiteowl HEVC transcoding PR
Subtitles: SRT files with 'forced" subtitles

Expected behavior: forced subtitles will be automatically enabled

Notes: Forced subtitles are correctly enable when playing the same movie back through a web browser.

Screenshot shows that on playback forced subtitles are not enabled.

IMG_20221117_194406349

### PR DESCRIPTION
**Pull request by therealguy90**
## Changes

Modified video player to mimic behavior of jellyfin web player, where subtitles load immediately when the video is loaded, according to user settings. Returns old functionality mentioned in #850.
Sets selectedSubtitleIndex to default subtitle.
Apologies for the duplicated PR, thought this would take longer.
Might also help with #1259, as this might remove some of the dependency on the system settings for captions

## Issues

Fixes #850

### CODE REVIEW

**Comment by therealguy90** [comment]
Leaving this as a draft for now. Definitely need some code cleanups and solve an issue where the subtitles don't load when the user presses next video.

**Comment by candry7731** [comment]
Have you been able to get the next video default subs working? Let me know if you need help on this.

**Comment by therealguy90** [comment]
I have, actually. I've been using my branch as my daily driver for about a week now and found no issues with the subtitles.

**Review by jimdogx — COMMENTED** [review]
This isn't working for me.

I have:
Preferred subtitle language: English
Subtitle mode: Only Forced
Burn subtitles: Auto

But when I play a movie, even though it shows "Forced" as selected, it's not actually showing any subtitles.  If I select "None" and then re-select "Forced", it shows subtitles but not in English.

I then tried the release build 1.6.6 and even though I had to manually select "Forced", it played them correctly in English.

**Pull request closed without merging**
