### PR TITLE
Fix Season Row Size

### PR DESCRIPTION
**Pull request by candry7731**
Fix Issue #794 

**Changes**
Changed row width from 1800 to 1700

**Issues**
Reports in issue #794

### CODE REVIEW

**Review by alanazar — APPROVED** [review]
Tested it and it displays correctly now

**Review by alanazar — APPROVED** [review]
Tested again \ works great

**Review by alanazar — APPROVED** [review]
Looks great!

**Review by 1hitsong — CHANGES_REQUESTED** [review]
The season scroller adjustments looks good.

I'm not a fan of the change to the Cast & Crew header. The text looks too high. It's touching the top of extras background. IMO, it was fine where it was before.

image

**Comment by alanazar** [comment]
> The season scroller adjustments looks good.
> 
> I'm not a fan of the change to the Cast & Crew header. The text looks too high. It's touching the top of extras background. IMO, it was fine where it was before.
> 
> image

You're right, top padding needs to come back. I think it was removed by mistake

**Comment by alanazar** [comment]
Tested it and it looks great

**Review by neilsb — APPROVED** [review]

**Review by 1hitsong — APPROVED** [review]

**Comment by 1hitsong** [comment]
To be merged 9/26 unless an issue arises.

**Pull request merged**
