### PR TITLE
Detect when content buffering hangs

### PR DESCRIPTION
**Pull request by neilsb**
Detect when Roku _hangs_ trying to download content from the server.

**Changes**
When buffering content from the server, start a timer that checks (every 10 seconds) that the Buffered Percentage has increased form the last check.  If there has been no increase, display a dialog to the user and return to the previous screen.

Once the video starts playing, disable timer.

**Issues**
Refs #189

### CODE REVIEW

**Comment by dkanada** [comment]
What endpoint are you using to download the content? I also saw hangs in my client until I switched to another endpoint.

**Comment by neilsb** [comment]
> What endpoint are you using to download the content? 

We're using `/Videos/{Id}/stream`

**Comment by dkanada** [comment]
I fixed the hangs by switching from progressive streaming to HLS streaming, maybe it would also fix your issue.

**Review by cewert — COMMENTED** [review]
This looks good to me but not sure how to test that it works during a hang. My media loaded as normal

**Comment by neilsb** [comment]
I've got a sample that I can provide you with.  Would be interesting to see if it causes an issue on other devices too for confirmation.

Since we're adding a listening for the video play state change changing, it probably makes sense to capture the "Error" state here too, and display a suitable warning.  I can get that added too.

**Comment by neilsb** [comment]
Added catching of general errors during playback.  This can be tested by shutting down the JF Server during playback for example.

**Comment by anthonylavado** [comment]
I would like to test this, but I'll need a sample to test with.

**Comment by anthonylavado** [comment]
I tested with the content that Neil provided. Both direct played to my Roku, with no issues and no hangs. They appear to have been automatically downconverted to Stereo.

**EDIT:** I realize I need to re-test, as I think I did so with this PR applied

**Review by anthonylavado — APPROVED** [review]
Approving because this should work, in theory, though we can't replicate the issue right now.

**Comment by neilsb** [comment]
Rebased on master

**Pull request merged**
