### PR TITLE
Display poster image for folders

### LINKED ISSUE #425: Folder items do not display images on the Roku app.
**Describe the bug**
Folder items do not display images in the Roku app, even if one is set on the server.

**To Reproduce**
1. Set up a Library categorized as "Other" on the server
2. Add a folder with subfolders to the Library
3. Add an image to the subfolder on the server
4. Navigate to this library using the jellyfin-roku app

**Expected behavior**
If a folder has an image set, it should display this image.

**Additional context**
I have an "Other" Library set up on my local install. Subfolders within this library have images set. These images display in the web client and also the iOS client. The roku-client does not fetch images for these folders.

### PR DESCRIPTION
**Pull request by ghost**
**Changes**
Added the necessary attributes in GridItem.brs to the "Folder" type. Updated FolderData.brs and FolderData.xml to mimic the "Video" type, and called the newly defined setPoster() function in setFields().

**Issues**
Fixes #425.

### CODE REVIEW

**Review by neilsb — COMMENTED** [review]
This looks good.  Only small issue is that when browsing Folders from the main library collection (When this is turned on in the user prefs) is that the top level is the Library folders, which don't have portrait images

image

This is more a problem with the ItemGrid component than your changes, and that component it needs updated to handle different sized items anyway (for Music Albums, etc)

At the moment, can I suggest that as a temporary measure we maybe don't set the `posterURL` when the type is **CollectionFolder**, and this will leave those specific folder types just as blue backgrounds?  If it's commented it should be fine until the ItemGrid is updated.

**Comment by ghost** [comment]
Yes - this makes sense. However, I am unable to replicate this view for testing.

> This looks good. Only small issue is that when browsing Folders from the main library collection (When this is turned on in the user prefs) is that the top level is the Library folders, which don't have portrait images

How do I turn this on in the user prefs? Is it on the client?

**Comment by anthonylavado** [comment]
@jd1123 I believes the setting Neil is referring to is server wide.

Try this:
- Go to the Dashboard, then Libraries
- Go to the Display tab, then enable "Display a folder view to show plain media folders", as seen here
79DE3893-D462-4ACC-9758-B245C425F55C

**Comment by ghost** [comment]
@anthonylavado - thanks for that!

@neilsb - I added a conditional to address the concern listed above.

**Review by neilsb — APPROVED** [review]
Works great.  Thanks.

**Pull request merged**
