### PR TITLE
Added Favorites row to home screen

### PR DESCRIPTION
**Pull request by candry7731**
Added Favorites row to home screen
Updated background color to dark gray to work better with backlit tv's

### CODE REVIEW

**Comment by neilsb** [comment]
Still seems to have the problem that once you go into the TV Guide, there's no way back out without exiting the app.

**Comment by candry7731** [comment]
> Still seems to have the problem that once you go into the TV Guide, there's no way back out without exiting the app.

I removed that change. Will debug more later.

**Comment by neilsb** [comment]
Looks pretty good.  Only thing I noticed is that the request for favourites is not limited, so if a user has 2000 items marked as favourites they'll get all of them back and a row 2000 items long.  Think it would make sense to limit this to something reasonable, maybe 30 or so?

**Comment by candry7731** [comment]
Sure we can do that, do you want to make the edit or should I?

**Comment by candry7731** [comment]
Or do you think we should add a "load more" button at the end of the
row.... that will fetch 30 through 60, so on and so forth....

**Comment by neilsb** [comment]
> Or do you think we should add a "load more" button at the end of the row.... that will fetch 30 through 60, so on and so forth....

I personally don't think that's necessary on the front page.  Users can switch to the "Favourites" view on the Movie Browsing page, and there's a PR to enable that on the TV Shows, Live TV Channels and TV Guide screens too, so if someone is looking for something specific I think they'd be quicker going to the appropriate library and using the Favourite filter there.

**Comment by candry7731** [comment]
I see what you are saying in that each folder can be sorted by favorites
however I have 10 folders and sometimes I forget what movie or tv show is
in what folder. So it might take me 10 minutes to find the favorite movie
that is in folder 4.... I like having the ease of access right on the home
screen and having it in each folder.

I will work on getting the guide to update based on favorites, by showing
favorite channels at the beginning of the guide..

**Comment by neilsb** [comment]
With this PR (and #477) I think it would make sense to wait until the Client Side Options/Preferences are in place, since this changes the UI in way that makes it different to how Web currently works. This way it means we'd not be forcing a change on the users.

**Pull request closed without merging**
