### PR TITLE
Add BIF Image Support - Using Jellyscrub Plugin

### PR DESCRIPTION
**Pull request by 1hitsong**
**Changes**
Adds BIF image support to video streams when scrubbing. This relies on the Jellyscrub plugin to provide API endpoints.

See it in action: https://twitter.com/1hitsong/status/1553892325490827264

### CODE REVIEW

**Review by jimdogx — APPROVED** [review]

**Comment by jimdogx** [comment]
I don't know what kind of voodoo this is, but I installed the plug-in and it works. 😄

**Comment by TwitchBronBron** [comment]
The latest player code in the `unstable` branch seems to be missing the jellyscrub bif lines introduced in this PR. Any idea where they went?

This PR:

image

latest unstable branch (notice the jellyscrub lines are missing):

https://github.com/jellyfin/jellyfin-roku/blob/4dbde139949c0dbdf54b27776c1e65ba3d00bd3c/source/VideoPlayer.brs#L278-L282

**Comment by 1hitsong** [comment]
@TwitchBronBron We removed it in pr #791 

I didn't know when I wrote this that official clients aren't to add code supporting 3rd party plugins.

**Comment by TwitchBronBron** [comment]
So, what's the long-term goal for trickplay/thumbnail/bif support on Roku then? Do we have to wait potentially a long time for official support for these things? Couldn't the jellyfin team make an exception for some of these things until there are official alternatives available?

**Comment by 1hitsong** [comment]
> So, what's the long-term goal for trickplay/thumbnail/bif support on Roku then?

I believe the server/core team is in discussions with the plugin author to bring the functionality into the core API.

> Do we have to wait potentially a long time for official support for these things?

Yeah, I'm afraid so. Official clients can not rely on plugins for functionality. The last thing we want is to have one of our clients beholden to an outside force. What would happen if they changed their code? Or if they didn't like how we implemented their work? Or a security issue was found and they didn't want to fix it? etc. etc.

> Couldn't the jellyfin team make an exception for some of these things until there are official alternatives available?

That's a question that's above my pay grade. 😄 Perhaps @anthonylavado has an answer for that one.

**Comment by anthonylavado** [comment]
I don't have the best answer here, other than what's already been explained. Right now it will still take _some_ time, but we want to get new features added in a faster fashion.

We've been hashing out [segment skipping](https://github.com/jellyfin/jellyfin-meta/discussions/30), next up would be to have the discussion on trickplay/scrubbing previews (this [thread](https://github.com/nicknsy/jellyscrub/issues/44) should be a new discussion on jellyfin-meta).

I had an additional long thing written out, but the short answers are:
- Though additional setup is required, there could be a support burden with split features (available in one place but not others, see SyncPlay)

- We want to add new features in a maintainable way, and we've got some heavy lifting to do for that. We've been burned by it before (again, see SyncPlay)

- We also don't want to take forever to add things. For the small size of the team, we're trying to get all our ducks in a row to make it easier and speed up releases (see the prolonged 10.8 cycle, which we are trying to actively break from)

**Pull request merged**
