### PR TITLE
QOL and wording changes to Server Select and Login Screens

### LINKED ISSUE #589: Back button not working on SetServerScreen
**Describe the feature you'd like**
When a user presses the back button on SetServerScreen, I think it would be more user-friendly to exit the app or to show an exit app dialog that will ask the user to exit the app.
On "Roku Developers" web page says that the app must exit the app or show an exit app dialog when the user presses the back button on the main scene. I know that SetServerScreen is not the main scene but in some parts of the user experience, it is.
I just suggest that this feature should be added.

### PR DESCRIPTION
**Pull request by Any-Fuel-5635**
This is the first of a few changes I would like to contribute to the project. This commit, while simple, is focused on the end user and their initial perception when loading the app for the first time. I would like to, over time, bring the login and menu system to be more in line with the more modern workflow of the Web application, but tailored to the design principles of Roku for ease of use. 

Wording changes, key-press changes to the submit, save credentials, and submit buttons to be slightly more intuitive. The goal is to make the first steps of loading the app more clear and smooth to a non-experienced end user. 

A very simple PR. In the future I would like to present some potential design changes to the side bar to streamline navigation, but those changes are not present in this PR. Thank you for your time and consideration.

### CODE REVIEW

**Comment by Any-Fuel-5635** [comment]
Updated localization changes to match the previous commit. There are now separate translations for Enter a username and Enter a password, and the Enter a Value.,. was retained in the translation files in the event an input value is needed in the future, this can still be utilized.

**Review by neilsb — CHANGES_REQUESTED** [review]
Welcome, and thanks for your contribution.  The button navigation and text changes all make sense.

The translation stuff in Roku is not great, and it's an ongoing desire to sort our own translation logic to improve things.  In general, however, you only need to make changes to the _source_ (or primary) translation file; which in our case is `locale/en_US/translations.ts`.  Once that's done, the online tool that we use ([Weblate](https://translate.jellyfin.org/projects/jellyfin/jellyfin-roku/)) will pick up the change and make it available for translation in all other configured languages.    So while it's commendable you updated all the the translation files there is no real need to do that as our community will generally do this.  Also, I assume you used something like Google Translate which is a good starting point, but community translations will generally be done by a native speaker of the language and will likely translate any phrases in a more natural way which online translation tools may not do.

The other thing is that since the source text is currently used as the translation key (which is one of the things that we want to look at changing) the other text that was changed (e.g.  "Pick a Jellyfin server from the local network" => "Select an available Jellyfin server from your network:") will now not be translated.  What the inbuilt translation code will do is look for an item in the translation file with the Source value equal to "Select an available Jellyfin server from your network:" which now won't be found.  The way to fix this is to just update the original text entry in the `locale/en_US/translations.ts` file with the new text, and Weblate will take care of the rest.

**Comment by Any-Fuel-5635** [comment]
Got that fixed and verified translations now work properly on my end. Furthermore, I performed necessary localization en_GB translations along with en_US. I flipped my Roku over to German and the original, translated values prior to my original PR are now correctly translated once again. Also when using the Roku in German, the Roku's login keyboard had a non-translated value at the top that was found in ConfigList.brs: "Enter the" was English only, and was followed by a translated ConfigField.label for the words "Username" and "Password" in whatever language I was using on the Roku. It pays to sometimes use the Roku in a different language, apparently.

**Comment by jimdogx** [comment]
Looks good.  I think we try not to include package-lock.json in our PRs though.

**Comment by Any-Fuel-5635** [comment]
Added a change that allows the spinner to give visual feedback with every refresh when hitting back on the server select screen. The screen won't just break anyone, and has some added functionality. Exit app using home button or back from the home screen. Json changes came along with ropm install. I removed the one line that was added (didn't seem to matter if it was there or not) and re-ordered the other two lines to match the original.

**Comment by alanazar** [comment]
Tested this and it works fine

**Comment by jimdogx** [comment]
Works!  Nice first PR.

**Review by neilsb — APPROVED** [review]
Great work.  Thanks!

**Review by alanazar — APPROVED** [review]
Tested it and it works fine on Roku - approving solely based on this
Code is a bit too much for me to review - sorry.
Q: Translation files should be remove from this since they update automatically?

**Comment by neilsb** [comment]
> Q: Translation files should be remove from this since they update automatically?

Future PRs shouldn't have them included, but don't believe they require to be removed from this PR since the work has been done.  Weblate should handle the automatically, and if they cause any issue we can tackle it directly.

**Pull request merged**
