### PR TITLE
Create Movie Grid View and new default setting

### LINKED ISSUE #899: Grid layout reduced to 1.5 rows
**Software Versions**
Jellyfin Server Version: 10.7.5
Roku Client Version: 1.6 build 2

**Describe the bug**
The view of videos after selecting a media folder used to show a grid with rows and columns filling the screen.  In this version there is only a row and a half and a large mostly blank space above (it has just the title and duration).

**How To Reproduce**

1. Go to a media folder
2. Scroll 

**Expected behavior**
Old layout 

**Connection Information**
Is server local or remote?  Local

Is server connection http or https?  http

### PR DESCRIPTION
**Pull request by 1hitsong**
**Changes**

1. Creates a new Movie Library view called Grid
2. Create a new User Setting type called Radio
3. Creates a new User Setting that sets a default view to use in the Movie Library if the user has not already selected a view. This is needed so if the user wants to use grid for everything, they don't have to manually set it on every library or sub folder.

**Issues**
Fixes #899

### CODE REVIEW

**Comment by neilsb** [comment]
The `Item Titles` and `Return to Top` settings for `Media Grid` don't appear to be being respected.  They maybe shouldn't apply to this, but if that's the case it's possibly confusing having them under the same section in the user settings.

Are we looking at just phasing out the `Item Grid` throughout the app?

**Comment by 1hitsong** [comment]
Sorry @neilsb. I sometimes forget y'all can't read my mind and if I don't tell y'all where my head's at, y'all won't know.

I'll check out `Return to Top`. That's an oversight. 

I'm going to add a 3rd option to `ItemTitles` in a followup PR and use it.

- Always Shown
- Always Hidden *NEW*
- Shown on Focus

**Comment by 1hitsong** [comment]
> Are we looking at just phasing out the Item Grid throughout the app?

I haven't planned on removing it everywhere, but at least in locations that have customized settings/functions/views/etc. 

I'm not a fan of having "If libraryType = "whatever"` all over the place. I'd rather separate the views so we can customize them all we want and have no fear of messing anything else up. Plus, it makes testing easier since the view is only used in 1 spot.

**Comment by 1hitsong** [comment]
`Return to Top` fixed. Missed a return true, so it was falling into a reload.

**Comment by jimdogx** [comment]
I might be misunderstanding the new user setting, but when I switch between Presentation and Grid, it doesn't change the view of "Movies".  It only changes the view of other libraries (Collections, 4k Movies, Anime, etc).

**Comment by jimdogx** [comment]
Per discussion, this appears to work correctly.  As long as there is another PR for ItemTitles 😄

**Review by jimdogx — APPROVED** [review]

**Pull request merged**
