### PR TITLE
Fixed URL for issue#95

### PR DESCRIPTION
**Pull request by piajesse**
**Changes**

Just changed the URL to apply to newer jellyfin instances
**Issues**

#95

### CODE REVIEW

**Comment by piajesse** [comment]
This is my first merge request, please let me know what I could have done to make it better

**Comment by crobibero** [comment]
What happens if the base url set in Jellyfin isn’t /jellyfin?

**Comment by bisby** [comment]
The issue with this is that every person has a different base URL. Hardcoding it to `/jellyfin/` will break it for more people than it fixes for.

A true solution would be to somewhere at the "enter the server" to ask for base URL. The enter the server bits need to be completely reworked as well.

However, as is, this isn't a thing we can merge.

**Comment by piajesse** [comment]
I'm gonna close this request and ask for more info on the original issue, I thought in the last update it was forced to /jellyfin/, not to where you can make it custom. And /jellyfin was default.

Thanks guys for the heads up!

**Pull request closed without merging**
