### PR TITLE
Refactor deviceCapabilities, fix vp9, and make 6 channel videos downmix if possible

### PR DESCRIPTION
**Pull request by sevenrats**
## Changes
- Refactor deviceCapabilities.brs
  - Use separate functions for each type of profile
-  Fix bug in VP9 profile and level support detection (profile/level detection was completely broken but is now fixed)
- Only allow 8bit videos for the h264 codec
- Allow the roku device to downmix multichannel audio for users with stereo speakers instead of transcoding down to 2 channels
  - e.g. 6 channel aac files direct play with this PR and my stereo setup instead of "direct streaming" like they do on unstable

### CODE REVIEW

**Comment by sevenrats** [comment]
really i feel like we need a user setting if we can't get more specific with the cause.

**Comment by cewert** [comment]
You're the only one getting the distorted sounds right now. We need to verify it's not just you before we hardcode it or make a user setting for it.

**Comment by cewert** [comment]
~~Setting this to draft. Everything works with one big exception - video files that are transcoded to preserve multichannel audio play as the should but fast forward and rewind no longer work as well as the length of the video showing 0.~~

EDIT: I moved this code to it's own PR #1466. Everything in this PR is working now and ready for review

**Review by 1hitsong — APPROVED** [review]
lakerssuperman and I both threw all we could at it and the stated goals appear to be honored. 

Neither of us were able to test VP9 support.

**Pull request merged**
