### PR TITLE
Update Authorization header

### PR DESCRIPTION
**Pull request by neilsb**
Replace legacy `X-Emby-Authorization` header with `Authorization`

### CODE REVIEW

**Comment by TwitchBronBron** [comment]
Will this prevent older versions of jellyfin from working properly?

**Comment by neilsb** [comment]
> Will this prevent older versions of jellyfin from working properly?

It will prevent the Roku client working on versions of the server before the change was made, which looks to be March 2019.  But I doubt there are many people running a version of server that old.... 😕

**Comment by TwitchBronBron** [comment]
Do the various other jellyfin clients have a standard for how far back server versions they support?

**Comment by crobibero** [comment]
The standard is latest major version (10.7.x)

**Review by crobibero — APPROVED** [review]

**Review by anthonylavado — APPROVED** [review]

**Pull request merged**
