### PR TITLE
Create global audio player

### PR DESCRIPTION
**Pull request by 1hitsong**
Creates a global audio player component. Moves audio player playback reporting into new global component.

This is step 1 of allowing us to have a mini audio player that can continue to play music as users move around the client.

As a user, you should experience no change in playback functionality from the PR.

### CODE REVIEW

**Comment by cewert** [comment]
Fix merge conflict please then I will test

**Review by cewert — CHANGES_REQUESTED** [review]
I believe it crashed when I hit "<<" to go to previous track while playing an album.

```
253:*     if m.top.audio.state = "playing"
254:          m.top.audio.control = "stop"
255:      end if
256:  
257:      if m.global.queueManager.callFunc("getPosition") > 0
Source Digest(s): 
pkg: dev 1.6.3 148bff51 Jellyfin

'Dot' Operator attempted with invalid BrightScript Component or interface reference. (runtime error &hec) in pkg:/components/music/AudioPlayerView.brs(253)
```

**Comment by 1hitsong** [comment]
> I believe it crashed when I hit "<<" to go to previous track while playing an album.
> 
> ```
> 253:*     if m.top.audio.state = "playing"
> 254:          m.top.audio.control = "stop"
> 255:      end if
> 256:  
> 257:      if m.global.queueManager.callFunc("getPosition") > 0
> Source Digest(s): 
> pkg: dev 1.6.3 148bff51 Jellyfin
> 
> 'Dot' Operator attempted with invalid BrightScript Component or interface reference. (runtime error &hec) in pkg:/components/music/AudioPlayerView.brs(253)
> ```

Exactly where the merge conflict originally was. I'll take a look.

**Comment by cewert** [comment]
It looks like you just need to switch these two lines from `m.top.audio` to `m.global.audioPlayer` ?

```
    if m.top.audio.state = "playing"
        m.top.audio.control = "stop"
    end if
```

**Comment by 1hitsong** [comment]
Fixed. There was a secondary bug that could occur when going back from item 1. All fixed and ready for review.

**Review by cewert — APPROVED** [review]
Looks good to me. I couldn't break it and it worked great 👍 

I would like to see it say "Track 1 of 10" or "Track 1 / 10" when the music is playing. Maybe that's nitpicking and definitely has nothing to do with this PR but thought I'd mention it.

**Pull request merged**
