### PR TITLE
Fix transcoding problem when using 10.8 server

### LINKED ISSUE #670: roku does not transcode
**Describe the bug**

Attempts to direct play video instead of transcode. It does not start any sort of playback. I get An error was encountered while playing.

**To Reproduce**

1. login to account with remote access
2. play hevc movie 
3. error occurs 

**Expected behavior**

Transcode due to remote connection

**Logs**
```
[2022-06-25 03:46:22.856 +00:00] [INF] [14] Jellyfin.Server.Implementations.Users.UserManager: Authentication request for "joan" has succeeded.
[2022-06-25 03:46:22.857 +00:00] [INF] [14] Emby.Server.Implementations.Session.SessionManager: Current/Max sessions for user "joan": 1/0
[2022-06-25 03:46:22.858 +00:00] [INF] [14] Emby.Server.Implementations.Session.SessionManager: Creating new access token for user 901a218d-10ab-44e6-b026-3041eafb0297
[2022-06-25 03:46:42.145 +00:00] [INF] [164] Jellyfin.Api.Helpers.MediaInfoHelper: User policy for "joan". EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
[2022-06-25 03:46:42.145 +00:00] [INF] [164] Jellyfin.Api.Helpers.MediaInfoHelper: RemoteClientBitrateLimit: 4000000, RemoteIp: "0.0.0.0", IsInLocalNetwork: False
[2022-06-25 03:46:42.146 +00:00] [INF] [164] Jellyfin.Api.Helpers.MediaInfoHelper: StreamBuilder.BuildVideoItem( Profile="Anonymous Profile", Path="/media2/movies/300 (2006)/300 (2006).mkv", AudioStreamIndex=2, SubtitleStreamIndex=-1 ) => ( PlayMethod=Transcode, TranscodeReason=ContainerBitrateExceedsLimit ) "media:/videos/7e1274b8-5614-d443-d2a7-d7d25ce27d0d/master.m3u8?MediaSourceId=7e1274b85614d443d2a7d7d25ce27d0d&VideoCodec=h264,h265,hevc,hevc&AudioCodec=ac3&AudioStreamIndex=2&VideoBitrate=3552000&AudioBitrate=448000&AudioSampleRate=48000&MaxFramerate=23.976025&api_key=<token>&SubtitleMethod=Encode&TranscodingMaxAudioChannels=6&RequireAvc=false&Tag=91abfd2a23884b8c589c99ad218380bf&SegmentContainer=ts&MinSegments=1&BreakOnNonKeyFrames=True&hevc-level=153&hevc-profile=main10&hevc-audiochannels=6&h264-profile=high,main,baseline,constrainedbaseline&h264-level=51&aac-audiochannels=6&TranscodeReasons=ContainerBitrateExceedsLimit"
[2022-06-25 03:46:43.780 +00:00] [INF] [67] Emby.Server.Implementations.Session.SessionManager: Playback stopped reported by app "Jellyfin Roku" "1.4.12" playing "300". Stopped at "0" ms
[2022-06-25 03:46:48.940 +00:00] [INF] [25] Jellyfin.Api.Helpers.MediaInfoHelper: User policy for "joan". EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
[2022-06-25 03:46:48.940 +00:00] [INF] [25] Jellyfin.Api.Helpers.MediaInfoHelper: RemoteClientBitrateLimit: 4000000, RemoteIp: "0.0.0.0", IsInLocalNetwork: False
[2022-06-25 03:46:48.940 +00:00] [INF] [25] Jellyfin.Api.Helpers.MediaInfoHelper: StreamBuilder.BuildVideoItem( Profile="Anonymous Profile", Path="/media2/movies/300 (2006)/300 (2006).mkv", AudioStreamIndex=2, SubtitleStreamIndex=-1 ) => ( PlayMethod=Transcode, TranscodeReason=ContainerBitrateExceedsLimit ) "media:/videos/7e1274b8-5614-d443-d2a7-d7d25ce27d0d/master.m3u8?MediaSourceId=7e1274b85614d443d2a7d7d25ce27d0d&VideoCodec=h264,h265,hevc,hevc&AudioCodec=ac3&AudioStreamIndex=2&VideoBitrate=3552000&AudioBitrate=448000&AudioSampleRate=48000&MaxFramerate=23.976025&api_key=<token>&SubtitleMethod=Encode&TranscodingMaxAudioChannels=6&RequireAvc=false&Tag=91abfd2a23884b8c589c99ad218380bf&SegmentContainer=ts&MinSegments=1&BreakOnNonKeyFrames=True&hevc-level=153&hevc-profile=main10&hevc-audiochannels=6&h264-profile=high,main,baseline,constrainedbaseline&h264-level=51&aac-audiochannels=6&TranscodeReasons=ContainerBitrateExceedsLimit"
```
**Screenshots**

**Additional context**
It works on direct lan access, and other streaming methods other than roku. It however does not play remotely. Thus why I think it is trying to direct play instead of transcode. Direct plays on lan, remote no go just outputs the error. I am not sure if it is just not transcoding or what, because roku app doesn't feature custom bit rates. I have set bit rate via admin dashboard for user and overall server to no avail.

### PR DESCRIPTION
**Pull request by neilsb**
In the current device profile, we specify that we support h264 profile level up to 5.1, whereas the Roku specification says they only support 4.0,4.1. In in the 10.7 releases, the maximum Profile Level the server would use was 4.1.

@nyanmisaka explained that hardware decoders may be able to decode higher profile levels but with some quality implications (e.g. 5.2 may play on 4.x hardware with macroblock artifacts).  This seems to be the case with Roku when Direct Playing, but when transcoding the device will have more strict checking using the info from the play, so will just refuse to play.

In order to allow a user to reduce transcodes, and attempt direct play of videos where the only reason for transcoding is an unsupported profile level, a user setting was added.  If the direct play fails, the transcoding url will be used instead.

**Changes**
- Update Device Profile to correctly set max supported h264 profile level to 4.1
- Add user option to allow user to attempt to direct play h264 media where only the Profile Level is compatible.
- Add logic in Video Player to force direct play in cases when user setting is true, and video is only transcoding due to profile level
- Add logic in Main for when video ends, to replay video using Transcoding if requested

**Issues**
fixes #670 #651

### CODE REVIEW

**Review by 1hitsong — APPROVED** [review]
Tried several files that previously failed and all played without issue.

**Review by whiteowl3 — APPROVED** [review]

**Comment by whiteowl3** [comment]
in deviceCapabilities.brs, the "Value" of the "hevc" "VideoLevel" needs to be the float multiplied by 30, in my tests.
https://stackoverflow.com/questions/69983131/whats-the-difference-between-ffprobe-level-and-h-264-level
such as 
```
{
                "Type": "Video",
                "Codec": "hevc",
                "Conditions": [
                    {
                        "Condition": "EqualsAny",
                        "Property": "VideoProfile",
                        "Value": "high|main",
                        "IsRequired": false
                    },
                    {
                        "Condition": "LessThanEqual",
                        "Property": "VideoLevel",
                        "Value": StrI(5.1*30),
                        "IsRequired": false
                    }
                ]
            }
```
~~but, to be clear, this has NOT fixed transcoding on my infra.  it only avoids transcoding everywhere it can.  when something still must transcode, it still failing for me on 10.8.x~~
other parts of my infra caused this, transcoding is working as expected with these changes.

**Comment by whiteowl3** [comment]
some of my subtitle changes are also required to prevent the erroneous transcoding, but im not sure which ones. probably just ass/ssa profiles of either embed/external type would be sufficient.

**Comment by neilsb** [comment]
> in deviceCapabilities.brs, the "Value" of the "hevc" "VideoLevel" needs to be the float multiplied by 30

Good catch, thanks.  Updated.

**Review by cewert — APPROVED** [review]
I had one file that wouldn't play because it needed transcoding that now plays fine with this PR. I also played a bunch of random files that needed transcoding and they all played as expected.

My setup is pretty simple though: local only server, 1080p TV, and a 2.1 soundbar.

**Comment by 1hitsong** [comment]
Left a comment in the chat, but will put it here for a paper trail.

I tested this again on the files I had problems with and everything worked without issue.

**Comment by funkybunch** [comment]
Upon merge I believe this also fixes #694

**Pull request merged**
