### PR TITLE
Add basic renovate config

### PR DESCRIPTION
**Pull request by crobibero**
Mentioned in https://github.com/jellyfin/jellyfin-roku/pull/618

This uses the org file as the base (https://github.com/jellyfin/.github/blob/master/renovate-presets/default.json)

### CODE REVIEW

**Comment by cewert** [comment]
This looks perfect, thank you.

I've never used renovate before. Do you recommend we merge this as-is or should we be configuring this first?

**Comment by crobibero** [comment]
Doesn't look like Roku uses that many depenencies, I know the web repo had a good amount of customization.
https://github.com/jellyfin/jellyfin-web/blob/master/.github/renovate.json

For now I recommend just sticking with the default and customizing as needed



Note that the Renovate app needs to be activated in the repo before this file does anything

**Review by cewert — APPROVED** [review]
Waiting on #618 to merge

**Comment by crobibero** [comment]
Closing in favor of https://github.com/jellyfin/jellyfin-roku/pull/623

**Pull request closed without merging**
