### PR TITLE
Add Rotten Tomato score to Movie Details

### PR DESCRIPTION
**Pull request by thomabx**
If Rotten Tomato score is available for media, display it on movie details. Deletes the child if there is not to correct spacing.

**Changes**
Adds rotten tomatoes fresh and rotten images.
Added label for genres.

### CODE REVIEW

**Comment by anthonylavado** [comment]
We have SVG for these somewhere. I want to say it’s in the Android TV repo.

**Comment by thomabx** [comment]
> We have SVG for these somewhere. I want to say it’s in the Android TV repo.

I saw those. I don't think SVG is supported by Roku. The [Roku docs for Poster](https://developer.roku.com/docs/references/scenegraph/renderable-nodes/poster.md) say only PNG and JPG are supported. But the docs are not always up to date. I wasn't able to get the SVG to display.

**Review by neilsb — APPROVED** [review]
Works as described.  Just out of interest, how do you get the critic score populated from an external source?

**Comment by thomabx** [comment]
> Works as described. Just out of interest, how do you get the critic score populated from an external source?

The server populated the metadata. It's either from Open Movie DB or The Movie DB.

**Review by cewert — APPROVED** [review]
Looks good 👍

**Pull request merged**
