### PR TITLE
Single Screen/Screen re-arch

### LINKED ISSUE #41: Use a Single Scene
**Is your feature request related to a problem? Please describe.**

Roku Docs suggest using a single Scene: https://sdkdocs.roku.com/display/sdkdoc/Scene 

We appear to have multiple Scenes that all extend Scene which should be avoided if I'm reading these docs correctly.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

I'm still trying to wrap my head around this and very well may not know what I'm talking about.

### PR DESCRIPTION
**Pull request by bisby**
**Changes**

A drastic change to move everything to a single scene, with the views now showing up as children to this single scene, which we handle as a stack. This makes transitions faster and simpler.

Also moves a lot of the components around so that the scoping works out a bit better (ie, certain fields no longer send up signals, it just tells the parent that something is changed), and if the parent can't handle it, it escalates.

Things still causes a bit of a ruckus, and we'll want to wrap a lot of this in abstractions and clean up, but for now, it's looking great.

Also moves the search screen to the side panel.

**Issues**

Fixes #41 and #79 
But creates a bit of backslide. I wasn't under the impression TV shows were working quite yet. but this definitely breaks them if they did. Also breaks collections a bit.

### CODE REVIEW

**Comment by cewert** [comment]
Here's my notes from testing:

- Selecting collections and TV libraries no longer work
- Selecting a collection or TV library once gives me the alert as expected and waits for me to select OK. Selecting it a second time shows me the alert again but then automatically closes it
- (EDIT: this bug existed before this PR. I'm using "TMDb Box Sets" plugin) Clicked a movie library and then selected a collection. App crashed `Use of uninitialized variable. (runtime error &he9) in pkg:/source/api/Items.brs(155)`
- When viewing a movie library, my "cursor" got stuck on the pager.
-- On page two and then when back down to the pager and tried to go back up to the poster list. debug console showed constant loading of movies. Spitting out Warnings about setting a nonexistent overview field. One time it crashed completely the other time it just loaded movies for 5 minutes till i stopped the app.
-- I was on page 4 and selected page one. No hang or crash just stuck down there.

- Started playing a movie then hit back button to exit. Movie detail screen loaded but my "cursor" couldn't be seen and wouldn't show up no matter what arrow i pushed. Hitting back took me back to the movie list as expected.

**Comment by cewert** [comment]
The movie list screen only shows 2 rows instead of 5 like before, was that intentional?
and yea TV shows did work before but the TV show detail screen/season list needed work anyway so not a huge deal

**Comment by bisby** [comment]
The 2 rows instead of 5 was "intentional" in that i changed it to get faster loading while dealing with constant loading for testing. it wasn't something that technically needed to change. although only 20 (and half of 20-30) show up on the screen at a time. I could see the argument either way.

Also just looked into it. The infinite loop is because:
* The paginator is set to observe the "pageSelected" field. Which is a button node.
* When a page is selected, the node is set into the field, so that the details can be scraped from it. Details are used to reload the list, then the focus is moved to the list.
* Moving the focus to the list moves the focus OFF pageSelected's node... which modifies the node... which triggers a field change... which looks to the observer like a page has been selected.

The resolution was just to put the page number into the field. `"4"` doesnt change when focus moves. so the field should only ever change on keypress accepting a page number.

(Good catch, I was way too far down the rabbit hole when I started trying to get pagination to work.)

Also, on subsequent up/downs, somewhere in there, the pager was being set as the "last focus" for the node. so it was moving focus to itself. added in an explicit "move to the picker" (which means we'll have to be consistent with naming wherever we use a paginator) and that should be fixed.

**Comment by bisby** [comment]
> Started playing a movie then hit back button to exit. Movie detail screen loaded but my "cursor" couldn't be seen and wouldn't show up no matter what arrow i pushed. Hitting back took me back to the movie list as expected.

This point is vaguely addressed with a TODO about picking the appropriate "last focus" for the details page (its because there is a nested focus on this page). Probably easy enough to fix but the whole fried brain thing. Was hoping to make it abstract enough to always detect when there is further nesting to do. Added a work around to at least make it function.

> Selecting a collection or TV library once gives me the alert as expected and waits for me to select OK. Selecting it a second time shows me the alert again but then automatically closes it

Apparently setting the dialog dialog to `close = true` has impacts. Now it close = true, close = false ... which doesnt re-open it but does let subsequent opens work.

**Comment by cewert** [comment]
Gave it another quick test.

The alert when selecting an unsupported library still automatically disappears for me. I noticed it stays on the screen if i hold the OK button down. Don't know if it did that before

The pager works as expected but the "footer" isn't showing up - the overlay with the dark background color so you can see the page numbers. The numbers are still there but are shown over the posters.

Also noticed the favorite and watched buttons don't work on the movie detail screen

Great job on all of this btw :+1:

**Comment by bisby** [comment]
Fixed favorite/watched buttons. Added the footer behind the pager. Can't replicate the alert for unsupported lib issue really. Not with the the android app remote anyway.

**Review by cewert — APPROVED** [review]

**Pull request merged**
