### PR TITLE
Add audio track selection to video player OSD

### PR DESCRIPTION
**Pull request by 1hitsong**
## Changes
Adds audio track selection popup to video player's OSD

## Demo
https://github.com/jellyfin/jellyfin-roku/assets/3330318/70d06fe3-3a9e-4c28-9207-b09a449e4b18

### CODE REVIEW

**Comment by jimdogx** [comment]
Verified:
1. Can select alternate track.
2. Can switch back to original track.
3. If alternate track is selected *before* playing, Select Audio dialog shows that the alternate is already selected.
4. Switched back and forth a bunch of times 😄

**Review by jimdogx — APPROVED** [review]

**Comment by tjlouie** [comment]
Was this new feature added? I'm unable to see the audio track selection in the OSD, tested with multiple .mkv files with multiple audio tracks. There is no icon to the right of the "CC" icon on multiple Roku devices on the 2.0.7 client and Jellyfin server 10.9.6

**Comment by jimdogx** [comment]
This was merged to the Master branch, not the 2.0.z branch.  So it would go out with the next major release (2.1.0 or 3.0).

**Comment by mikewhitby** [comment]
Thanks @1hitsong this is really useful

**Pull request merged**
